### ISSUE TITLE
Improve slideshow view

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#1013]
I'm not sure what we should do with this feedback:

"https://dlmenetwork.org/library/catalog?f%5Bcho_type_facet.en_ssim%5D%5B%5D=Sound%3AInterview&page=2&view=slideshow
Home-clicked Type-Sound-Interviews- changed view to slideshow
No information is shown about the audio, even when hovering over the icon.
When clicking on the icon, it does not show the metadata of the item, only a link, and a play and pause button, which is displayed on a pop up window and the link is not clickable"

**Comment by ggeisler** [comment]
I believe we intentionally don't show much metadata in slideshow view, because showing a potentially vertically lengthy section of information could interfere with the visually-oriented intention of the slideshow view.

A few things complicate this pattern a bit in DLME and might account for the feedback.

1. The one bit of metadata we do show in slideshow view in DLME appears to a form of the item's identifier, which isn't usually very useful to the end-user. 

<img width="708" alt="Screen Shot 2020-06-05 at 9 02 28 AM" src="https://user-images.githubusercontent.com/101482/83898639-0abfa780-a70c-11ea-895f-21999c57120d.png">

This is intended to be the item title, not the identifier, as in Exhibits, for example:

<img width="708" alt="Screen Shot 2020-06-05 at 9 03 45 AM" src="https://user-images.githubusercontent.com/101482/83898702-20cd6800-a70c-11ea-9ba6-c8a9ee9e749f.png">

I'm not sure how that ended up as the identifier rather than the title in DLME, but we should fix that if possible.

2. Even in Exhibits don't make the title linked to the item show page when in slideshow view. I wonder if anyone remembers if we omitted linking to the show page for a deliberate reason? Displaying the title and linking it to the item show page would match the behavior of the other search results views. We could potentially link the image itself, but I worry about unintended clicking there, given the forward and back click targets on the side of the image.

3. In the feedback submitter's example, the results include audio files. That seems to make the play and pause buttons a bit ambiguous, since if you're thinking about audio you might be primed to expect them to be audio play and pause buttons, rather than the slideshow controls.

We do show hover text for the icons that indicates they are for playing and pausing the slideshow (I might file a ticket for improving the wording a bit). So given that, and the fact that audio is a very small part of this and probably all other existing Spotlight exhibits, I'm not sure we need to do anything about that part right now. If we can improve the first two items I mention above, that seems like a sufficient improvement in the near term. I'll also try to think about a longer-term improvement to account for audio and video items.

**Comment by ggeisler** [comment]
Closing this since we decided to turn off the slideshow view in DLME.
