### ISSUE TITLE
Broken bidirectional element

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#1055]
Go to "view-source:https://dlmenetwork.org/library/catalog/b17775905" and search for `<li class="breadcrumb-item active"><bdi`. I can't tell if there are any noticeable effects.

**Comment by ggeisler** [comment]
I don't know if it is due to the broken `bdi` element, but the breadcrumbs do not display the current item as they should.

On an item show page, the current item title should be displayed as the final node of the breadcrumb, unlinked.

Do a search in any Stanford Spotlight exhibit and [select an item](https://exhibits.stanford.edu/fitch/catalog/tv206kh7995) to see the intended display. For example:

<img width="647" alt="Screen Shot 2020-08-26 at 12 47 16 PM" src="https://user-images.githubusercontent.com/101482/91349777-9fc9be00-e79a-11ea-8888-ed26b5767be7.png">


---

Versus what we have now in DLME:

<img width="647" alt="Screen Shot 2020-08-26 at 12 47 40 PM" src="https://user-images.githubusercontent.com/101482/91349792-aa845300-e79a-11ea-94dc-926f2710673d.png">

**Comment by jkeck** [comment]
This is caused by attempting to truncate the breadcrumb string, but since the title contains HTML (the `<bdi>` element), we're getting malformed HTML.

It seems like the most straight forward way to approach this could be to use a css based truncation strategy so that it will support both HTML and plain text.  I'll push a PR up to Spotlight to propose that.
