### ISSUE TITLE
Redesign home page to allow rows of content categories

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#1066]
From QNL: "Redesign of the main page to make it more engaging. We thought of going towards the “Netflix” style, where you have several rows for content categories and then several items in each row. Categories could by time periods, types of items, data providers, maybe some selection of subjects etc."

This ticket relates to https://github.com/sul-dlss/dlme/issues/1029

**Comment by jacobthill** [comment]
Check with QNL to see whether scrolling is required. If not, this requirement will be met by https://github.com/sul-dlss/dlme/issues/1029

**Comment by jacobthill** [comment]
Horizontal browsing is necessary

**Comment by ggeisler** [comment]
For future planning and prioritization purposes, I want to note that I believe this is a fairly large ticket in terms of both design and development effort. There are going to be significant UX and accessibility considerations to do this in a good way. And I'm not 100% certain it is even a good idea; what makes sense for a streaming media library interface doesn't necessarily make sense for a digital exhibit website.

If we do decide to do it, we might consider doing it in a way that makes it easy to restrict its use in non-DLME exhibits (e.g., assuming it is a new widget, we ensure that this is a widget we could hide from Stanford Exhibits curators, if we decide it's not something we want to see in our exhibits).

**Comment by jacobthill** [comment]
@ggeisler these are good points to keep in mind. My expectation is the QNL would not be unreasonable if we could document why this is technically a bad idea. I think the argument would need to go beyond keeping the DLME implementation of Spotlight synced with Spotlight upstream; that's important to us but less so to them. From a user perspective, alone, this seems like a valuable feature to the QNL team, and it makes sense to me. I am happy to explore any technical challenges that arise as we think through the side effects of implementing it and try to argue why this is a bad idea (if we decide that it is) with QNL if that is necessary. So I see three paths forward:

1. We implement this as QNL asks and push changes upstream to Spotlight.
2. We implement this as asked but hide this feature from Stanford Exhibits curators.
3. We come up with clear reasons why this is a bad idea for DLME and convey those to QNL.

**Comment by ggeisler** [comment]
@jacobthill Yep, that sounds right (I think [1] and [2] could really be the same solution, as long as we make it possible for a Spotlight implementer, such as Stanford Exhibits, to omit availability to curators of the new widget in their implementation. We might already have an easy way to do this for widgets in general, I'm not sure).

When I have time I'll explore a bit deeper so we can better judge if we need or want to make a case for [3].

**Comment by jacobthill** [comment]
I just want to note that I don't think we want to drop the facets from the home page; trading facets for categories would be a poor trade for the user in my opinion. I think we want to figure out a way to keep both.

**Comment by ggeisler** [comment]
Below are preliminary details for assessing the potential of the two main options for this feature:

- Option 1: Static browse group widget
- Option 2: Horizontally scrolling browse group widget

After we finalize which option we are going with, there are additional details omitted here that I'll add to produce a final design.

## Option 1: Static browse group widget

This approach simply adds two minor things to the existing browse categories widget:
1. A title (the title of the selected browse group) above the row of browse category blocks
2. A “View all” link above the row, which when selected leads to the browse landing page with that browse group’s filter selected. 

In other words, this approach gives the user a preview of a given browse group by displaying the first three of the browse categories in that group. The user can then select “View all” to see a page with all browse categories in that group.

From any browse group page, the user can also use the filter buttons at the top of the page to easily move to another browse group page and see all of the categories in that group.

Here’s a mockup with three instances of this option for the widget, using _Time period_, _Cultural artifacts_, and _Geographic region_ as example browse groups to feature:

<img width="1127" alt="Static-widget" src="https://user-images.githubusercontent.com/101482/104073277-7f8b2080-51ca-11eb-920b-671bad97a140.png">

Although this approach is pretty straightforward, here’s an interactive mockup where you can select the “view all” link for the either of the first two browse groups to see how it takes you to the filtered browse group page:

https://xd.adobe.com/view/924d4473-0809-4664-81e3-e50e1c480f06-c71e/


## Option 2: Horizontally scrolling browse group widget

In this approach each featured browse group initially displays the first three browse categories from the group but also enables the user to horizontally scroll to see additional browse categories from the group without leaving the homepage.

There are several important compromises we need to make with this option:

- To accommodate the affordances required for horizontal scrolling, the size of the browse category blocks needs to be reduced  (to 185x138 from the current 214x160 at the LG desktop size). From an image perspective this reduction seems acceptable, but it also reduces the space available for the browse category label, which will result in more frequent label wrapping, etc.

- At phone viewport widths (SM and XS), we’d have to reduce both the number of visible browse category blocks (to 2 from 3) and at least at the smallest viewport sizes, the size of the blocks even further (e.g., less than 170px wide each). This would cause further issues with the category block text labels wrapping, since the blocks would then be at least 45px narrower than at the LG viewport width. (Alternatively, we could decide to not enable horizontal scrolling at the smallest viewports, but that will of course entail extra work to handle.)


An interactive mockup of this option is at: https://xd.adobe.com/view/03f1195e-00c0-4afe-bd26-e27518412bc8-56a2/

(Click on the page to see the hotspots. For example, on the first mockup page you can click the partial Browse category 4 under Time period to see the Next navigation arrow that would actually be shown on hover. From the next page you can click on the Previous navigation arrow to return the row to the beginning (this icon is backwards because of a bug in XD’s publishing feature. Click on the site footer to see an example where the three widget instances are in different states). 

### Static mockups:

**Initial state with three instances of the Horizontally scrolling browse group widget:**

<img width="1127" alt="Initial-state" src="https://user-images.githubusercontent.com/101482/104073325-9f224900-51ca-11eb-893b-b1e255ea8765.png">

---

**Next navigation control to scroll the Time period widget (displays on hover):**

<img width="1127" alt="Next-control" src="https://user-images.githubusercontent.com/101482/104074580-b7479780-51cd-11eb-8048-94c6b7037e53.png">


---

**State after using the navigation control to scroll the Time period widget:**

<img width="1127" alt="After-moving-to-next-group" src="https://user-images.githubusercontent.com/101482/104073387-c547e900-51ca-11eb-9bc6-1a933c47f3ea.png">

---

**Example state where user is hovering over the next control for the Time period widget; has previously scrolled once in the Cultural artifact instance; has previously scrolled to the end of the Geographic region instance:**

<img width="1127" alt="Example-three-states" src="https://user-images.githubusercontent.com/101482/104073398-d133ab00-51ca-11eb-98a2-586870254ff0.png">



## Summary
I’m trying to be objective in seeing the value of Option 2, and maybe I’m missing something, but I personally see many more advantages to Option 1: 

- Homepage is visually cleaner; there are no navigation controls needed, no partial views of the browse category blocks needed
- Browse category blocks don't need to be reduced in size as they do with Option 2 (to accommodate navigation controls), which also means we're not reducing the amount of space available to display the browse category labels
- For a user who wants to see more than a handful of the browse categories in a given browse group, fewer clicks are required (i.e, one click to get to the browse group landing page to see all categories in the group -- with possibly some vertical scrolling for large groups), versus using Option 2’s horizontal scrolling, where a click is required for every three browse categories
- Same solution works at all breakpoints (Option 2 will require some type of special consideration for narrower mobile viewports)
- No accessibility/keyboard navigation concerns (Option 2 will require us to think through how the keyboard and screenreader user accesses and triggers the previous and next controls for horizontal scrolling)
- Relatively low development effort to implement

The only advantage I see in Option 2 is:
- The user can easily see more than a few browse categories in a browse group without leaving the homepage context

It’s true that the horizontal scrolling pattern of Option 2 can be found on media sites with lots of categorized content (though I wouldn’t call it a _standard_ pattern; YouTube and AirBnB don’t use it on desktop, for example, and they feature multiple, deep categories on the home/interior pages). And in DLME we already have (or will when the browse groups feature is implemented) pages dedicated to displaying all browse categories in a group. So I’m struggling to see how the benefits of Option 2 justify the costs and compromises required.

**Comment by asmaaalkuwari** [comment]
@ggeisler Marcin and I have discussed the suggested mock-ups for the homepage design, and we believe that going with the 2nd option with the inclusion of the hovering navigation arrows is most suitable with the assumption that it also includes the "View All" option to be available as well. With this option, we believe that it will keep the main page more engaging for the users, as well as being less busy with the hovering effect. We assume that with this design, there will be a capacity of having 10-15 tiles per category. 
One thing to consider is to make use of all the space of the full width of the page. 
There has been an issue raised in regards to resizing the images down, and we would like to understand what exactly is the issue with that?

**Comment by asmaaalkuwari** [comment]
> @asmaaalkuwari What do you mean "make use of the full width of the page"? Are you suggesting we remove or move the faceted navigation on the left of the page?
> 
> Can you be more specific about the "issue raised in regards to resizing images down"? I'm not sure what you are referring too.

Hi @jacobthill For the first inquiry regarding the "make use of the full width of the page", please refer to the attached document for your reference. I have highlighted and took a screenshot to make the issue more clearer. Also  we've found other user experience issues that we've highlighted in the document. I hope we can add them as part of the new design as well. https://docs.google.com/document/d/1d7RPZVplHLiHqWWE39xQOvbtGQhGlHWfk52fV_2GDnE/edit?usp=sharing 

As for the "issue raised in regards to resizing images down", according to @ggeisler's comments in the summary (referring to the point 2 of option 1), we would like more clarity on that.

Thanks,

**Comment by jacobthill** [comment]
@asmaaalkuwari I cannot access the Google document you shared. Can you give permission please? Also I don't see any comments from @ggeisler under point 2 option 1 related to resizing images. I assume you are talking about the bullet points under option 2. I think what @ggeisler is saying is that the images we use for the categories e.g. 
<img width="162" alt="Screen Shot 2021-01-12 at 9 20 02 AM" src="https://user-images.githubusercontent.com/37662787/104326166-65e22580-54b7-11eb-9d61-06d6093d52fc.png">
will need to be reduced in size to fit on smaller screens (tablets and phones, etc.) so that a user can swipe left to right and scroll horizontally. Reducing the image will also reduce the space available for the title, since the titles sit on top of the images, which means longer titles will wrap to the next line. We are likely to see some undesirable text effects where titles no longer fit neatly into a single line, etc. So we have to come up with a solution for that. I think if you have more specific questions @ggeisler can answer them.

**Comment by mwerla** [comment]
@jacobthill As I am around the computer, I changed the sharing settings - anyone with the link should be able to access the document now.

Regarding the other comment, @ggeisler wrote "To accommodate the affordances required for horizontal scrolling, the size of the browse category blocks needs to be reduced (to 185x138 from the current 214x160 at the LG desktop size)." It's hard for us to understand why this reduction is really needed.

**Comment by ggeisler** [comment]
@asmaaalkuwari @mwerla

- Our main content area is fixed in width at desktop viewport widths (LG = 690px, XL = 825px). This assumes we continue to display the facet sidebar as @jacobthill indicated earlier we probably want to do.
- We need to visually indicate to the user that horizontal scrolling is available (for a desktop-oriented website, we can't simply assume the user knows this is possible)
- If we want to avoid the visual clutter of previous/next buttons always visible (for each horizontally scrolling row), we have to visual indicate the horizontal scrolling affordance in some other way. The most obvious solution is what Netflix does: show a partial image at the end of the visible row (and the start of the visible row after it has been scrolled); the partial image makes it more obvious that there is more to the row that can be seen. I tried to make this very clear in my mockups above.
- To make room for partial images (which have to be wide enough to accommodate a previous/next button, e.g., 42px wide, plus 10px gutter to separate from the adjacent image) we have to reduce the size of the width of the images in the row. For example, at the LG viewport size, the current image size of the browse category blocks are 214x160. To make room for the horizontal scrolling affordances, the image size of the browse category blocks must be reduced to 185x138.
- Because our display of browse category blocks includes a text label that is displayed within the image block, the reduction in image block size means there will be more cases where the text label will need to wrap to fit within the image block size

To avoid reducing the image block size, we'd have to go with an option that presents an always-visible navigation affordance. Here are a couple of options where we keep the image blocks the same size as they currently are and display visible scrolling affordances:

In both examples below, assume that that user has not used the horizontal scrolling for the top and bottom rows, but has scrolled once in the middle row.

### Alternative A
<img width="1126" alt="Screen Shot 2021-01-12 at 8 50 26 AM" src="https://user-images.githubusercontent.com/101482/104338274-90ca7a80-54b3-11eb-9084-57fceff67a6d.png">

### Alternative B
<img width="1126" alt="Screen Shot 2021-01-12 at 8 50 03 AM" src="https://user-images.githubusercontent.com/101482/104338225-8314f500-54b3-11eb-934d-c0cc1d21d1cb.png">

**Comment by mwerla** [comment]
@ggeisler Thanks for the quick clarification. I think that we have two separate issues here:
1) **Space we want to dedicate for the main content section.** As you wrote, now it is 825 px for the main content part plus 285 for the menu with filters visible on the left. I think we should discuss utilizing more horizontal space on the screen. We could also discuss moving the menu with filters to gain more space. It could become for example a dropdown menu somewhere near search in the main navigation bar. @jacobthill I propose to make a separate ticket for that and continue the discussion there, including other problems reported in Asmaa's document.

2) **The way to show that X number of categories in a row it's not all, there is a scrolling possibility.** I think this is independent of the problem (1) above because we will have this challenge for any screen size anyway. From what I could see on other pages, and from your examples, we have two options:
A) Horizontal scrolling controls within a single bar are always visible - in such case, it's not important if the current resolution allows displaying X number of full category tiles or if the border tiles are cut off because the navigation is visible anyway.
B) Horizontal scrolling controls within a single bar are visible on hoover - we need to ensure the cut on border category tiles in a row so that it suggests to the user that there is more.

I checked a few websites and option (B) seems to be more tricky to implement properly and probably is not worth the effort.

For option A, with the always visible scrolling controls, I like the approach that you presented in Alternative B above. I like it because it's not covering the tiles. Moreover, I think that it should be much easier to translate such a design into a mobile version, even for a screen width allowing only a single column of content.

**Comment by ggeisler** [comment]
I'm putting design details for this into two new tickets:

- #1142 - Display horizontally-scrolling categories in a browse group
- Configure horizontally-scrolling browse group rows

**Comment by ggeisler** [comment]
Closing this since the final designs for this feature have been added to new tickets.
