### ISSUE TITLE
Revisit options to deal with http content

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#1074]
American Numismatic Society does not use https which prevents us from displaying images. We have discussed this before with them and they seem reluctant to change this policy. QNL is concerned that the way their content looks in DLME  will reflect poorly on DLME in the eyes of the users. We need to revisit this issue to see if there is another solution. 

The same problem is occurring with CSIC data: https://dlmenetwork.org/library/catalog?f%5Bagg_provider_en%5D%5B%5D=Consejo+Superior+de+Investigaciones+Cient%C3%ADficas+%28CSIC%29

**Comment by mejackreed** [comment]
Relevant discussion here: https://github.com/sul-dlss/dlme/issues/795

**Comment by mejackreed** [comment]
I propose the following as the actionable pieces of work here. Based off of the following:
 -  DLME should be as inclusive as possible
 - Browser changes in the past year have started to disable mixcontent images


 - [ ] Implement a dynamic image proxy in DLME for HTTP thumbnails that DLME is trying to display. We should do this because: DLME content providers are often not able to offer HTTPS content, and we want to be as inclusive as possible for the project.
 - [ ] For DLME providers who provide IIIF content that is not HTTPS, do not proxy this content, and in fact do not try to display a IIIF viewer. We can still try to proxy their HTTP thumbs for display in search results and perhaps a show page, but we cannot proxy all of their webservices.

**Comment by jacobthill** [comment]
@mejackreed this sounds like a reasonable compromise to me. @mwerla what do you think? For context, there are two known providers that currently don't have https, one of them has iiif.

**Comment by mwerla** [comment]
@jacobthill For me, @mejackreed proposal makes perfect sense.

**Comment by jacobthill** [comment]
@mejackreed this doesn't seem to be working:

https://dev.dlmenetwork.org/library/catalog?f%5Bagg_provider_en%5D%5B%5D=American+Numismatic+Society

**Comment by mejackreed** [comment]
Yes, once this gets merged, it should start working: https://github.com/sul-dlss/dlme/pull/1111

**Comment by jacobthill** [comment]
Thanks for the clarification

**Comment by mwerla** [comment]
@jacobthill @mejackreed Looks like it's working now, right?

**Comment by jacobthill** [comment]
yes
