### ISSUE TITLE
Switch default search operator for end users free text searching from "OR" to "AND"

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/dlme#1106]
Requested by @mwerla on 2021-01-13 to behave more like expected Google search

[Search notes](https://docs.google.com/document/d/1nQ9LOmEkjqO70p3pMyjTPmovOjt2FDjuDnZBPKWhqOg/edit#)

**Comment by cbeer** [comment]
Can we clarify the expected behavior here? I'm nervous that significantly reducing the precision of our queries could have unexpected side-effects. Instead, if we could take a step back to look at the underlying problem (presumably, poor recall? or is this intended as a power-user feature?) with some example queries and documents that should/should not be returned, we might be able to provide a better search experience for our users. 

As written, I understand the request to mean e.g. a query for `Ibn Rashid` would return all the documents that have either `Ibn` or `Rashid` (5,542 documents for `Ibn`, 485 for `Rashid`) instead of just the 106 currently returned that have both Ibn and Rashid in the document [1], most of which are probably not about Ibn Rashid.

In our experience with search endpoints, this can be extremely frustrating or confusing to our users, and we've received some extremely negative feedback on other sites when the search recall is too broad. Power users sometimes do want the ability to explicitly specify an "OR" query, and we have several options for accommodating that  (e.g. an advanced search page, or allowing the user to use the search query `Ibn OR Rashid` to get those ~6k documents). In practice, we don't see this happen very often, and usually just by exhibit curators who use this to craft browse categories.

[1] our current algorithm is a little more nuanced than this, although it was borrowed from other sites and hasn't been tuned for DLME.

**Comment by mejackreed** [comment]
From linked search notes above:

`فريدريك جون جولدسميد`

DLME - 159 results
https://dlmenetwork.org/library/catalog?utf8=%E2%9C%93&f%5Bagg_provider_en%5D%5B%5D=Qatar+National+Library&exhibit_id=library&search_field=all_fields&q=%D9%81%D8%B1%D9%8A%D8%AF%D8%B1%D9%8A%D9%83+%D8%AC%D9%88%D9%86+%D8%AC%D9%88%D9%84%D8%AF%D8%B3%D9%85%D9%8A%D8%AF

QDL: 96 results
https://www.qdl.qa/en/search/site/%25D9%2581%25D8%25B1%25D9%258A%25D8%25AF%25D8%25B1%25D9%258A%25D9%2583%2520%25D8%25AC%25D9%2588%25D9%2586%2520%25D8%25AC%25D9%2588%25D9%2584%25D8%25AF%25D8%25B3%25D9%2585%25D9%258A%25D8%25AF

There is concern I heard from @mwerla that using "OR" returns too many documents and that they have tuned QDL to use "AND".

We will look into how this change might affect the result set.

**Comment by mwerla** [comment]
@cbeer As I understand, at the end we basically agree :) To re-iterate my **assumptions** are the following:
- Most users are expecting from websites search behavior like Google or Wikipedia, where searching for Qatar Airways or pancake recipe will return info about specific airline / specific dish recipe. If they add more words to subsequent queries in a search process, they do it to narrow down the results (similarly to applying more filters).
- Most users will use just a few first results, so in case of a large recall with OR they will anyway focus on the first results provided by the ranking algorithm (which ideally should prioritize results containing all words from the query).
- Power users may use the OR operator, to achieve OR behavior. Lame users may simply issue separate queries for each word they would normally join with the OR operator, and in the end, they will get a similar result.

We did the same exercise for the Qatar Digital Library last year. First, we tested in with professional users from the library, and they liked the AND version. Then we pushed that into production and we didn't receive any complaints from users and parameters like the traffic from the search results page to specific items didn't go down.

**Comment by cbeer** [comment]
Thanks @mwerla. Can you provide more information about what you tried with QDL? We, too, have experience with testing and tuning relevancy and, as I mentioned, having it completely "OR" or completely "AND" had a negative impact on our users' experience. I'll provide a couple examples of how we've adjusted minimum term match based on user behavior and corpus:

- In Searchworks, Stanford's library catalog, we have about 10 million documents indexed and serve a wide variety of audiences, but general user behavior is oriented around finding a particular item or set of topical items (contrast with exhibits below..). Because the corpus is fairly large, we've been able to increase the "minimum match" (how many terms out of a query string must match in order to be recalled) and, to a point, each additional term does narrow the number of search results. However, we do see a significant number of "known item" searches that include pasting long citations, contained misspelled (or otherwise non-matching terms; perhaps the citation adds additional information not in a catalog record). To account for that, based on user testing and search evaluation, we tuned our matching to use "AND"-like behavior for the queries up to 8 terms long and then require 90% term matches beyond that.  

- In Exhibits at Stanford, with individual exhibits ranging from tens to hundreds of thousands of documents, a very strict minimum match can result in very limited recall. We also wanted to relax those requirements in anticipation of more casual user behavior compared to the library catalog, and serving users more interested in exploring than finding a known item. In this environment, we found that tuning to 6 matching terms required, and then at least 90% of terms beyond that was a good middle ground.

As far as I can tell, DLME is using a tuning that may have been beneficial for development and aggregation testing (allowing staff, testers, and data contributors to see a large set of aggregated results and tweak the relevancy by asking why it isn't higher/lower in the results instead of missing items that they might not even be aware of). To that end, it looks like DLME is currently set to just 2 required terms for 1-4 term queries, 3 required for 5 or 6, and then 90% after 7.

Off-hand, I agree that those seem very permissive, but instead of jumping immediately to requiring all terms, it would be my  recommendation that we:

- increasing the minimum match to something closer to Stanford's exhibits platform (as a starting point, at least), assuming that we expect similar types of users in both environments
- perform some log analysis to gather a set of user queries that will let us evaluate the impact; while we should expect the recall to be substantially reduced, we'd want look for instances where a query returns 0 results and evaluate whether this is a good result (because DLME has nothing relevant) or a frustrating or discouraging dead-end for users because we have relevant items that are now excluded (and then.. figuring out whether to tune the minimum match, or (more likely) add additional indexing/synonyms/stemming/transliteration/etc)
- finally, especially in something like DLME, we should also evaluate the impact on a variety of cross-collection searches. I'd be concerned that, due to varying metadata practices across institutions, a too-high minimum match may end up excluding results that may be relevant but are described differently depending on their source. Again, additional search tuning may need happen, but as users will, as you say, focus on the prioritized results, it seems safer to error on the side of recall (but not too much) than to deprive certain types of matches that, by aggregating so many collections together, DLME is in a unique position to serve.

Thanks

**Comment by jacobthill** [comment]
I'll hold off on linking my whole report for the moment. I think this is an example of the kind of ranking problem I think DLME has: In the query “slavery Persian Gulf”, none of the top 10 results are about slavery. They contain the terms “Persian” and “Gulf” but not “slavery”. Searching for “slavery AND Persian AND Gulf” returns 82 results. These should be the top 82 results. If we can improve in this area, I think its best to keep out `mm` settings as they are. If we can't we may need to switch them so that 1-3 token requires require all tokens to match.

**Comment by jacobthill** [comment]
To be clear, I don't want us to do this yet. I want to assess the difficulty level and use this ticket to surface any potential issues with this strategy.
