### ISSUE TITLE
Improve mobile navigation design

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#1108]
As a DLME user I would like a better mobile navigation design so that when I use the DLME app on my cell phone I will have a better navigation experience.

The majority of DLME users are accessing the application from a mobile device ~50%

Feedback from QNL UX designer:

- Three menus in the header, resulting in 2 hamburger icons on mobile and filters' header looking like main content header

<img width="163" alt="Screen Shot 2021-01-13 at 8 39 16 AM" src="https://user-images.githubusercontent.com/37662787/104459540-d9993680-557a-11eb-866d-a6bf1f18bb7c.png">

Needs to be considered in relation to https://github.com/sul-dlss/dlme/issues/1110

**Comment by ggeisler** [comment]
I'm closing this because I've created two new, separate tickets to address the separate issues raised in the original description of this ticket. See #1374 and #1375.

Note that I did not see any apparent user confusion with the search navigation on mobile when I viewed a bunch of user sessions, but of course there could've been confusion that wasn't apparent since I was just watching the sessions and didn't hear what the users were thinking about they used the site.
