### ISSUE TITLE
Improve design of gallery view

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#1136]
There is a lot of variation in the size of thumbnails provided from data providers, which results in a messy presentation of results in the gallery view.

![image](https://user-images.githubusercontent.com/562200/105093184-5f553e80-5ab3-11eb-83b8-2ba9e55fb094.png)

Can we add a consistently sized/styled container to create a cleaner presentation? See, for example, LoCs handling of different proportions of thumbnails:

![image](https://user-images.githubusercontent.com/562200/105093260-801d9400-5ab3-11eb-92b5-530f77702998.png)

**Comment by ggeisler** [comment]
@mwerla @jacobthill I've updated the gallery view of the results page in my local dev environment and made some screenshots. The layout is very similar to the LOC example above. I made screenshots with three different background colors for the box that contains the thumbnail image and caption (item title plus metadata fields). Basically, I started with white, but am not sure if the contrast with the site background color is too much (maybe a bit distracting). So I tried two dark variations. One uses the same background color as the facets that are adjacent to the result items. The other is pretty similar but has some blue in it (it's a very light variation of the blue in the site masthead).

Here's an example:

<img width="1233" alt="FFF-p-5" src="https://user-images.githubusercontent.com/101482/105259232-a6d9da00-5b48-11eb-8e66-b38d268934fc.png">

Go here for more examples and to compare the three color variations: https://projects.invisionapp.com/boards/SZ41JIUJK7Q/

A couple of notes:

- I only modified CSS, so I think we could do it relatively easily, if we decide we want to
- As Marcin mentioned in #1084, I added Type, Date, Creator, and Identifier as metadata fields to display. We might not want all of those, but it's easy to turn on and off different fields so Jacob could experiment to get the right set you want to show.
- Also from #1084, I hid the metadata field label from the display. Note that if we do this it has to be for all fields (i.e., we can't show/hide the label for some fields and not others)

**Comment by mwerla** [comment]
@ggeisler Thanks, the new design looks much clearer to me. Regarding colors, I like the darker variants, but I don't have a strong preference for which of the two darker ones we could go.

**Comment by mwerla** [comment]
There are issues with how long titles are handled - see below. I propose to cut the titles after +/- 3 lines.

https://dev.dlmenetwork.org/library/browse/group/manuscripts/astronomy-manuscripts

![image](https://user-images.githubusercontent.com/562200/106441512-2fcb0c80-648b-11eb-800b-1604aab28e53.png)

**Comment by mwerla** [comment]
Another problem is with "long" thumbnails - there is no max-width for a thumbnail and as a result the entire row height grows:

https://dev.dlmenetwork.org/library/browse/group/manuscripts/astronomy-manuscripts

![image](https://user-images.githubusercontent.com/562200/106441755-7de01000-648b-11eb-8b9f-1313f9a20f3c.png)

**Comment by ggeisler** [comment]
@mwerla 

> Another problem is with "long" thumbnails - there is no max-width for a thumbnail and as a result the entire row height grows

There is a `max-width: 100%;` property for the thumbnails. This enables the thumbnails to get as wide as the container (minus some the padding you see in your screenshot), if the dimensions of the source thumbnail are as wide as the container (second and fourth thumbnails in your screenshot). That is the goal of gallery view (versus list view): give the user as good a visual impression of the item as possible (if the user doesn't care about the visual aspect of the item they can just use list view).

We could replace the `max-width: 100%;` property with an explicit pixel value to ensure items with an extreme vertical aspect ratio (item 3 in your screenshot) don't get too tall, but that will make all thumbnail images more narrow and reduce the visual information gallery view is intended to provide. 

For example, here's that same results page with an `max-width: 100px;` setting for the thumbnail. It reduces the height of item 3 (item 7 in my screenshot), but at the cost of making all thumbnails on the page -- even ones that have a more horizontally-oriented aspect ratio (e.g., item 3 in my screenshot) -- much smaller, because they are now restricted to `100px` in width.

<img width="1148" alt="Screen Shot 2021-02-01 at 10 47 23 AM" src="https://user-images.githubusercontent.com/101482/106498229-52095e00-647c-11eb-8a42-135715e2721b.png">

---

Unless I'm missing something, the problem is not with how we're defining thumbnail sizes in gallery view, the issue is simply that the thumbnail images of DLME items come in a wide range of aspect ratios and there's no way to optimize the height of gallery view rows without going to an approach that displays only part of thumbnail images that don't match the ideal aspect ratio.

**Comment by jacobthill** [comment]
For the extra long titles, it is probably best to solve this by re-mapping them. I have this on my list of things to do when I revise the mapping.

**Comment by ggeisler** [comment]
@mwerla On the thumbnail width issue, a compromise we could make that seems reasonable to me is to leave the width alone (giving images with non-extreme aspect ratios as much width as is current in -dev) but to add a `max-height` property. This would only affect the thumbnail images with very vertical aspect ratios, making them shorter and more likely to be closer in height to other non-extreme images in the same row. For example, here's that results page with `max-height: 250px;`:

<img width="1148" alt="Screen Shot 2021-02-01 at 12 11 30 PM" src="https://user-images.githubusercontent.com/101482/106506589-25a70f00-6487-11eb-8930-7c9e881bc072.png">

---

The very vertical image (3rd in second row) is affected (it gets narrower as well as shorter), as is the one after it (slightly, but you can see they are now the same height while before they were different heights). Basically this would improve the outlier thumbnail images with extreme vertically-oriented aspect ratios but leave other images alone.

**Comment by mwerla** [comment]
@ggeisler Sorry - in my comment I should write max-height... I agree with you that we should limit the max-height - that's a minimum. But I see one benefit of even fixing the height of the thumbnail - the titles will start at the same level. It will be then easier to scan quickly through a row of results.

**Comment by mwerla** [comment]
@jacobthill Regarding the title mapping, would you have then two separate title fileds? Short for thumbnails and long for full display?

**Comment by jacobthill** [comment]
@mwerla we have an 'cho_alternative' field for alternative titles that display only in the full record view. I could map excess titles to that field.
