### ISSUE TITLE
Right align text in Arabic "contact us" prompt

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#1176]
<img width="677" alt="Screen Shot 2021-02-01 at 12 29 24 PM" src="https://user-images.githubusercontent.com/37662787/106495245-6dc73100-6489-11eb-8a76-7d79f5d6f192.png">

**Comment by mejackreed** [comment]
@jacobthill  this behavior in Arabic is the same as in English. And when switching to aligning (to either side) will offset the text from the form.

![Screen Shot 2021-02-01 at 12 33 31 PM](https://user-images.githubusercontent.com/1656824/106508519-baab0780-6489-11eb-8877-c5f1366d3d48.png)

@ggeisler can you please confirm this is the exepcted design?

**Comment by ggeisler** [comment]
@mejackreed I think the issue is with the CSS that is styling this text string. It's currently using a `text-align: center` property so when the line wraps, the second line is centered:

<img width="586" alt="Screen Shot 2021-02-01 at 12 59 05 PM" src="https://user-images.githubusercontent.com/101482/106511602-aec14480-648d-11eb-9ccc-daf86f167c19.png">


I think the solution is to update the CSS that affect the text-alignment of this string and make it `text-align: left` for English and do the usual thing to get the RTL equivalent for Arabic:

<img width="737" alt="Screen Shot 2021-02-01 at 1 04 34 PM" src="https://user-images.githubusercontent.com/101482/106511873-18d9e980-648e-11eb-9d07-282eb855a548.png">

**Comment by mejackreed** [comment]
Ok, so we want to remove the `text-align: right` from the form labels also on the form? (in English)

## Before
![Screen Shot 2021-02-01 at 1 19 08 PM](https://user-images.githubusercontent.com/1656824/106513375-22645100-6490-11eb-8369-a62a52e356e4.png)

## After
![Screen Shot 2021-02-01 at 1 18 57 PM](https://user-images.githubusercontent.com/1656824/106513383-242e1480-6490-11eb-9af0-aa45dca747c5.png)

**Comment by ggeisler** [comment]
@mejackreed I'm not sure I understand. I don't think this issue is about the field labels, just the intro text highlighted in my and Jacob's screenshots above.

Technically I think the Arabic version of the field labels should be left-aligned to be equivalent of the right-aligned English labels, but that is not as big of a deal in my mind.

**Comment by asmaaalkuwari** [comment]
I have checked the arabic alignment from my end, and it seems working fine.

**Comment by asmaaalkuwari** [comment]
Translation for the feedback form:
If you have any questions or comments regarding this item, please let us know using the form below:
إذا كان لديك أي سؤال أو تعليق بخصوص هذا العنصر ، يرجى استخدام النموذج أدناه

Question or comment: سؤال أو تعليق

Email address (optional): (البريد الالكتروني (اختياري
