### ISSUE TITLE
Spacing of text on item cards in gallery view results in partially obscured text

### ISSUE THREAD

**Issue by caaster** [sul-dlss/dlme#1177]
Please see the example below:
![Screen Shot 2021-02-01 at 9 50 19 AM](https://user-images.githubusercontent.com/3210225/106497466-ed95d100-6472-11eb-8f31-0130c6ebde0f.png)

**Comment by jkeck** [comment]
The strategy that has been implemented for truncating this content at a particular number of lines is to use line-height & the height of the element to calculate the number of lines present in an element.

The reason this is happening is because the particular field in question has arbitrary HTML contained within (which can have different font sizes/padding/etc). There may be an element that introduces some sort of sizing that may throw off the line calculation (in the example above it's the bottom margin on the `<p>` tags).  

One possible improvement might be to add a gradient effect to the bottom of a truncated element so that it "fades" into the element.  This would at least obscure more of the text (and might be less visually jarring).

Another potential avenue to look into would be to look into the element's direct children and use the bottom of any element that intersects the goal height to actually set the height.  This seems like it would be quite a bit more complicated to implement.

**Comment by ggeisler** [comment]
Noting that a minor related issue I noticed when watching some Hotjar sessions: occasionally the "more" toggle is displayed when there actually is no more text to display (I guess because the text is just the right length to trigger the need for the toggle, but because of the challenge Jessie described above, the text is actually completely displayed).

This isn't a major UX issue, but I did see a couple of users click on it and it revealed nothing additional, so they probably were at least mildly annoyed at having selected something that had no effect.

**Comment by ggeisler** [comment]
Given:

- My comment above noting that sometimes the calculation of whether there is more text to display is off slightly (presumably because of the presence of arbitrary HTML in the text, as Jessie suggested is the source of the problem), resulting in a "More" button with nothing more to display, and
- The challenge of finding an obvious way to mask partial lines of text that might or might not be immediately above the button (I've tried a bunch of CSS tricks to deal with this, but none seem feasible)

I wonder if the best solution is simply to strip out the arbitrary text from the HTML that is causing the problem? I guess I've lost track of why we think we need to preserve HTML text in metadata that comes from data providers, but if we  strip out at least selected HTML tags (i.e., only tags that affect font sizing) from the search result metadata before we display it, wouldn't that ensure that the currently imperfect calculations related to the "More" button would be more accurate?

**Comment by ggeisler** [comment]
@jacobthill I think this is a DLME-specific feature, so maybe the Spotlight label you attached is not applicable, depending on what you intend that label to represent.

**Comment by jacobthill** [comment]
@ggeisler I just want to check that I'm understanding this thread correctly. I don't see any arbitrary HTML in [this record](https://dlmenetwork.org/library/catalog/cambridge_genizah-5645). Here is [the gallery view](https://dlmenetwork.org/library/catalog?exhibit_id=library&search_field=all_fields&q=A+large+bifolium). We implemented a solution for identifying and removing HTML tags from partner metadata at transform so no HTML tags should make it into the IR (note: some records may need refreshing for this to take effect). If arbitrary HTML tags in the IR are the problem, we will be able to close this issue. Can you check the record above and let me know if I'm misunderstanding something?

**Comment by ggeisler** [comment]
@jacobthill If we've already implemented the `stripping HTML from partner metadata` solution, that's great. It seems like that should make this issue easier to solve.

As you note, your example record does still display the partially obscured text issue, so that suggests to me that there is something about the button toggle solution that needs to be tweaked. I don't know the details of how this solution was implemented, but I suggest we leave this ticket as actionable for a developer to investigate. Using the links you provided above, we can see that a record with no HTML in the metadata still displays a partially obscured text issue. So the task for a developer would be to look into the implementation of this button toggle and see if they can figure out what is causing it. It could be as simple as adjusting some CSS vertical margin/padding values, but that's just a hopeful guess.

**Comment by marlo-longley** [comment]
Hi @ggeisler and @jacobthill - I spent a while looking into this issue just now. A few things:

- The HTML is indeed stripped as it comes from the partner metadata, but we wrote our [own processor that wraps content in paragraph tags](https://github.com/sul-dlss/dlme/blob/f1b2eca3fd5b702a05c2aa581e7e5bde3bdc82b6/app/processors/paragraph.rb#L10). We then set the `description` field to use the paragraph processor [here](https://github.com/sul-dlss/dlme/blob/f1b2eca3fd5b702a05c2aa581e7e5bde3bdc82b6/app/controllers/catalog_controller.rb#L88). This markup wrapped in `<p>` tags is shared between different views, including the thumbnail view being addressed in this issue.
- It's true that the `margin-bottom` on these paragraph tags are causing this issue

I'm submitting a simple fix PR that targets the thumbnail view `<p>` tags and removes the margin.
