### ISSUE TITLE
Metadata Display

### ISSUE THREAD

**Issue by waynegraham** [sul-dlss/dlme#121]
The metadata displayed on an item page (http://staging.dlme.clir.org/library/catalog/stanford_jb757gw0658) does not visually flow (`dt` and `dd` tags). Can this be wider?

![1 degree graticule grid world 1 110 million 2012 digital library of the middle east dlme](https://user-images.githubusercontent.com/45000/29522120-2b825cda-8656-11e7-9f98-6c7377989e63.png)

**Comment by jcoyne** [comment]
I believe this is because spotlight expects these metadata to be presented on the right of the oembed as seen here: https://exhibits.stanford.edu/ua-maps-drawings/catalog/hn529bb6287 

Do we want to change the layout so that metadata is on the right, or change the style such that the metadata takes up the full width of the row?

**Comment by cbeer** [comment]
It seems like a 1-column layout is also popular in the community:

https://github.com/projectblacklight/spotlight/issues/1819#issuecomment-321246796

**Comment by anarchivist** [comment]
This one of the tickets that probably would benefit from @ggeisler's attention.
