### ISSUE TITLE
Embed Google analytics with Google Tag Manager

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#1220]
From Marcin: 

> One more thing – I just realized, that it would be great to switch the way DLME is connected to Google Analytics.
> 
> Currently, the GA tracking code is embedded in the DLME code. What we find much more flexible and powerful, is to use Google Tag Manager instead. It allows injecting any kind of tracking on the page, without asking the tech team for any work. It also makes it much easier to track things like scrolling depth on a page etc.
> 
> If you don’t have experience with GTM, I can easily create a configuration for DLME and send you the tracking code that should be placed instead of the current GA tracking code. The GA data collection would be still going to the same GA account, so we wouldn’t loose the continuity of data.

> Paste this code as high in the `<head>` of the page as possible:
> 
> ```
> 
> 
> <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
> 
> new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
> 
> j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
> 
> 'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
> 
> })(window,document,'script','dataLayer','GTM-T96MPMB');</script>
> 
> 
> ```
> 
> Additionally, paste this code immediately after the opening `<body>` tag:
> 
> ```
> 
> 
> <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-T96MPMB"
> 
> height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
> 
> 
> ```
> 
> Please let me know once that’s done in production, so I can verify if all works. I can provide similar code for dev environment if it’s easy to have different code snippets depending on the environment (there will be just a different GTM id).
> 
>

**Comment by mejackreed** [comment]
To move forward with this work, I'm going to suggest the following for development and project sustainability.

 - Create a Tag Manager account for DLME Network, similar to the DLME Network account for Google Analytics
 - Provide access to the same people at the same levels as the DLME Network Google Analytics account
 - Create three different environments (one for dev, stage, and prod) for the project see https://support.google.com/tagmanager/answer/6311518?hl=en
 
The development team will need access to TagManager to verify that our installation is being recorded appropriately. Because of some of the frameworks we are using a copy and paste of the Tag Manager snippets will likely yield incorrect metrics without additional developer intervention.

We will also have deployment configurations that will need to be updated to provide different TagManager environment configurations.

Does this sound like a useful process to pursue?

**Comment by jacobthill** [comment]
@mejackreed it sounds reasonable to me.

**Comment by mwerla** [comment]
@jacobthill @mejackreed Please let me know when we can expect this transition to GTM to happen in production. I initially created GTM account and generated the above tracking code for production environment, but it's fine for me to delete it if you are planning to create this on your own. Just add my google account (marcin@werla.pl) with enough privileges to modify the production GTM config. That will be very useful for me to do similar things like I did for QDL: HotJar tracking and scroll depth recording for each page.
