### ISSUE TITLE
Fix CloudWatch alarms for 502 errors alerting when state change is `INSUFFICIENT_DATA -> OK`

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/dlme#1268]
Currently as described in [#1248 (comment)](https://github.com/sul-dlss/dlme/issues/1248#issuecomment-844465029), we're seeing lots of CloudWatch alarms, and subsequently email alerts in the following case:

```
Alarm Details:
- Name:                       spotlight-production-elb-502-count
- Description:                Service spotlight-production has high 502 from elb
- State Change:               INSUFFICIENT_DATA -> OK
```

It seems like the `INSUFFICIENT_DATA` state means that there are holes in the time series data:

<img width="1370" alt="Cloudwatch graph showing timeseries data" src="https://user-images.githubusercontent.com/73732/118882894-81b46880-b8a9-11eb-9794-235a3e9af936.png">

We could fill those holes with zeros instead: <https://stackoverflow.com/a/63375758>. See also [metric math for CloudWatch](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/using-metric-math.html).

**Comment by kamchan** [comment]
I "think" I've made a fix just now.  There were alerts where it needed to handle missing data otherwise it will treat it as "insufficient data".   So the cloudwatch alerts should either now be in "OK" or "Alarm" states and sends email only during those transitions.  

For the 502 errors, currently the check is for alerting when within a two minute period there are more than two 502 occurrences.    If the project feels that it should check for more than one (instead of two) occurences before alerting, we can change that in terraform.    Looking at the past 24 hours,  there were about 20 two minute periods where a single 502 occurence was registered with one being at 2 occurrences.

**Comment by anarchivist** [comment]
Thanks, @kamchan - I'll keep an eye on it for the next few days, and plan to close it next week.
