### ISSUE TITLE
Truncate long titles

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#1293]
As the DLME data manager, I want to truncate the view of excessively long titles so that they don't clutter the screen for end users. Excessively long titles look unprofessional in the DLME web application but we don't want to permanently change the provided data. 

- [ ] In gallery and list views, use `line-clamp` as designed below to limit the number of lines for titles to 4 lines.
- [ ] In the item details view use `line-clamp` as designed below to limit the number of lines for titles to 2 lines.

**Comment by ggeisler** [comment]
@jacobthill Can you provide links to some items with what you consider long titles?

**Comment by ggeisler** [comment]
The most straightforward way to deal with long titles is to simply decide how many lines we think are acceptable for titles in different contexts and restrict the visible title to that. We can use CSS to limit the title to _N_ lines for each context and not have to worry about specifying character limits and dealing with media queries to handle different character lengths for different viewport widths. The CSS will limit the number of visible lines in each context and add an ellipsis at the end of any title that would exceed our line limit.

The only context where this solution isn’t completely satisfactory is on the item details page, since here I think the user needs to have easy access to the entire title. But instead of adding a “more” button or something to expand the truncated _heading_ title there, I suggest we display the title as the first _metadata field_ in the list of metadata fields on the item details page (that field is currently turned off). That way we don’t have to do anything special to handle the title in the heading; we can truncate it to prevent the page from looking weird when there are long titles, but we also give the user easy access to the full title in the metadata section. 

## General solution
I've tested the `line-clamp` approach below and verified it works in Chrome, Firefox, Safari, and Edge. [Caniuse](https://caniuse.com/?search=line-clamp) indicates the only browser that doesn't support it is IE (0.28% of our users), with Opera Mini and UC Browser "unknown", but even if those don't support it, those make up less than 2% of our users (and what they would see is probably just what they see now). 

```
  display: -webkit-box;
  -webkit-box-orient: vertical;
  -webkit-line-clamp: 2;
  overflow: hidden; 
```

## Contexts to apply solution to
The same CSS applies to each context, but we probably want to vary the number of lines in the `-webkit-line-clamp` property for each context below.

### Search results - gallery view
- 4 lines

<img width="1436" alt="Screen Shot 2021-12-16 at 11 01 01 AM" src="https://user-images.githubusercontent.com/101482/146424592-62c60dc1-f343-4485-855e-6b30320e4bbe.png">

### Search results - list view
- 4 lines

At comparable viewport widths, list view allows for longer text than gallery view, but since the entries for list view are already intended to be longer (e.g., we display more metadata in that view), I think we can afford to allow more vertical space for the title when necessary. Below is an example of 4 lines viewed on a phone, which is the worst case:

<img width="871" alt="Screen Shot 2021-12-16 at 11 10 39 AM" src="https://user-images.githubusercontent.com/101482/146425900-1ac8771b-e626-4ef0-968c-256df77ddc00.png">

### Search results - slideshow view
- 2 lines

The intent of slideshow view is to feature images, not text, so I'd suggest we display fewer lines here. (Also, I plan to recommend increasing the title font size in slideshow view in another ticket, so the distraction of showing more than a couple of lines of text will likely be greater than the example below indicates.)

<img width="1645" alt="Screen Shot 2021-12-16 at 11 29 30 AM" src="https://user-images.githubusercontent.com/101482/146428412-42534359-58a0-4652-8784-f9b90d4257f7.png">

### Item details page
- 2 lines
- Turn on "Title" metadata display for the Item details page

#### Before example
<img width="1173" alt="Screen Shot 2021-12-16 at 11 35 57 AM" src="https://user-images.githubusercontent.com/101482/146429396-940396c4-cdfa-4844-8c72-356157647ca0.png">

#### After example
Note that the truncated heading title requires less scrolling for the user to see the image window and the metadata area than the example above, but the full title is still available just below the image window, and takes up relatively little space since the font size is much smaller in the metadata section.

<img width="1173" alt="Screen Shot 2021-12-16 at 11 37 45 AM" src="https://user-images.githubusercontent.com/101482/146429591-e86e3c83-2a58-48a6-9773-9f343a69cc48.png">

**Comment by waynegraham** [comment]
I think `line-clamp` makes a lot of sense on most views. On the item view, I could see some potential for user frustration that there isn't an immediately obvious way to see the entire title until they scroll. I think if it comes up, we could investigate something like https://codepen.io/pbakaus/pen/OJLNNvm?editors=1100 (at least on the item view) to improve the experience or just keep the full-length text for the title on that one view.

**Comment by mwerla** [comment]
@jacobthill I checked the dev and the title above the content is truncated, but the metadata block does not include the full title field. https://dev.dlmenetwork.org/library/catalog/harvard_harvard-ihp-807

**Comment by mwerla** [comment]
Also the item title in the breadcrumb is very long and breaks the layout of the page, but maybe that's another task?

**Comment by jacobthill** [comment]
@mwerla the title is now configured to display in the item view. I remember talking about the breadcrumb but I don't remember what we decided. @ggeisler do you remember?

**Comment by ggeisler** [comment]
@mwerla @jacobthill You might have seen this by now, but the breadcrumb fix was handled in a separate ticket and PRs (I filed the breadcrumb issue in Spotlight because the core issue affected Spotlight more generally):

- https://github.com/projectblacklight/spotlight/issues/2787
- https://github.com/projectblacklight/spotlight/pull/2796

And then there are some DLME-specific related fixes:

- https://github.com/sul-dlss/dlme/issues/1497
- https://github.com/sul-dlss/dlme/pull/1498
