### ISSUE TITLE
Draft IIIf page in English

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#1354]
- [ ] Draft English text
- [ ] Review English text
- [ ] Translate into Arabic

**Comment by jacobthill** [comment]
Should we link to an external page so we don't have to worry about keeping it up to date? e.g. https://library.stanford.edu/projects/international-image-interoperability-framework/viewers?manifest=https%3A%2F%2Fdms-data.stanford.edu%2Fdata%2Fmanifests%2FParker%2Fwz026zp2442%2Fmanifest.json

**Comment by ggeisler** [comment]
That would make sense to me. If we go that route, I'd suggest we take some time to update the library site page. I don't think it's been updated much since it was originally created and while it's pretty generic and thus hard to get out-of-date, I think it would be worth spending some time thinking about how to enhance it a bit, given all the developments in IIIF since we first created that page.

**Comment by ggeisler** [comment]
Also, off-hand I don't know whether it might be better to just reference the IIIF.io site (or a particular page within that site) rather than the Stanford Libraries page. So that might be part of the investigative work to resolve this issue.

(It makes sense for us to reference the Stanford Libraries IIIF info page within our own applications, but since DLME is not branded as a Stanford application, I think there is more leeway in what page we send people to for more IIIF info.)

**Comment by mwerla** [comment]
Just to capture the outcomes of the discussion yesterday, we should link to https://iiif.io/. So no need to draft a dedicated page, but @jacobthill I am not sure if we have a dedicated task to make the link from the browser to the info page.
