### ISSUE TITLE
Announcements and updates subscription button not fully visible

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#1363]
<img width="993" alt="Screen Shot 2021-12-01 at 11 53 14 AM" src="https://user-images.githubusercontent.com/37662787/144278140-1a8b9f22-9148-4ae4-aaf1-ef329dc20cc5.png">

**Comment by waynegraham** [comment]
We might consider setting up a different account somewhere for this. The current system uses an iframe as there wasn't an integrated API. We're in the process of evaluating some newer systems for managing communications at CLIR, but we should definitely investigate if there's a solution that makes more sense for DLME specifically.

**Comment by waynegraham** [comment]
CLIR just launched a migration to a new form system (Hubspot) that uses an embed code instead of an iframe. I created a new form that can be used with the following embed:

```
    <script charset="utf-8" type="text/javascript" src="//js.hsforms.net/forms/shell.js"></script>
    <script>
      hbspt.forms.create({
        region: "na1",
        portalId: "20251227",
        formId: "c095dee4-2800-4bcb-92ea-1eae01bebddf"
    });
    </script>
```

While there's a bit of versatility in this system to change the font, colors, size, and buttons, it does not have the ability to change where the labels are for consistency with the Contact Us form but is consistent with the Feedback form.

**Comment by waynegraham** [comment]
Along with this, there is a link on the about/about page (https://dlmenetwork.org/library/about/about) with a heading for **Announcements and updates**. Perhaps this should link to the this page instead of the page outside the site?

**Comment by ggeisler** [comment]
Good catch @waynegraham, it does seem odd to embed an external form on one page and point out to the external version of that form on another. This is all probably @jacobthill's call, but unless I've misunderstood some of this discussion, I'd suggest the actionable steps for this issue are:

- Update the embedded form on `about/announcements-and-updates` to use the new Hubspot embed above
- Update the link on the `about/about` page, Announcements and updates section, to point to the `about/announcements-and-updates` page so users can fill out the new Hubspot form there

I can take a look at making whatever styling tweaks are needed and possible after the new form is embedded.

**Comment by waynegraham** [comment]
Here's the `iframe` target for the hubspot form: https://share.hsforms.com/1wJXe5CgAS8uS6h6uAb693wc21y3 

Height may need to be adjusted a bit more (550px seemed to do it) as there's a drop shadow that I can't seem to turn off for the form.

**Comment by thatbudakguy** [comment]
thanks @waynegraham! I've updated the link on the about page and embedded the new form.

**Comment by jacobthill** [comment]
@ggeisler do you have any styling suggestions for this form? It looks a bit out of place as is.

**Comment by ggeisler** [comment]
@jacobthill Yeah, I was planning on looking into that today. I saw the update yesterday and overall the form is nice (clean-looking and responsive) but the shadow bothered me (we don't use prominent drop shadows elsewhere on the site so that does feel out of place) and the color contrast, while fine, does make it more obvious this form comes from outside DLME.

Depending on how much control @waynegraham has over the styling at the Hubspot source, it might not take too much to up with a more integrated look:

<img width="1135" alt="Screen Shot 2022-02-04 at 9 24 45 AM" src="https://user-images.githubusercontent.com/101482/152565712-2798d9bf-61ff-4a2e-88cf-16e4c4b608dd.png">

@waynegraham If you can let me know whether you can adjust things like removing the box-shadow and specifying `margin-top: 0;`, etc. I can give you a short list of property updates to try to get closer to the example above.

**Comment by waynegraham** [comment]
@ggeisler Unfortunately there aren't options to set the background or set CSS classes in that UI (top using JS embed, bottom using iframe). I did an experiment and discovered that using the JS embed just provides the form without the halo though. There is another option I saw for "raw HTML form" that I need to check to see if there are styling options that you can apply to the fields. 

<img width="1294" alt="Screen Shot 2022-02-09 at 9 26 49 AM" src="https://user-images.githubusercontent.com/45000/153221586-8c649008-8f3c-4971-8d03-1d71884a2002.png">

**Comment by waynegraham** [comment]
Follow up that the raw HTML form in this system does not provide any ability to set CSS styles on the fields (it's meant to integrate with the HubSpot CMS). 

So I think the question is if we can use the `iframe` approach and live with the halo, or figure out a way to work around the code stripping for the embed code. 

For my 2 cents; I think the halo is fine for now if this might take any kind of significant time.

**Comment by mwerla** [comment]
@jacobthill No further comments from my side.
