### ISSUE TITLE
Link collections from each data provider in the contributors page

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#1379]
Depends on https://github.com/sul-dlss/dlme/issues/1327

We would like to expose each collection under the appropriate data provider in the contributors page. 
- [ ] The display value should be whatever value is in the `add_data_provider_collection`.
- [ ] The urls should use the `add_data_provider_collection_id` field since the collection names may change and we don't want the urls to change.
- [ ] We should also display item counts for each collection. Counts can be built from either of the above fields; they should effectively be the same

For the hierarchical type facet we build a field the takes `cho_edm_type` and `cho_has_type` and combines them e.g. if `cho_edm_type` = `Image` and `cho_has_type` = `Photographs` the new field = `['Image', 'Image:Photographs']`. We don't have anything similar for collection but, if needed, @jacobthill can build it.

**Comment by ggeisler** [comment]
@jacobthill For me to do any sort of design around this I think I need to better understand the data we're working with.

Can you provide specific examples of several data providers and each of the collections they offer? I think I'd need:

- Data provider name
- Link to each of their collections

I'd also want the items below, unless I can get them by following the link to the collection:
- Name of each collection
- Number of items in each collection

**Comment by jacobthill** [comment]
So that is a little tricky at the moment since collections aren't yet a thing in DLME. The data is there but we haven't exposed the `dlme_collection` field in the app yet.  I think the best way to see what we have is to look at https://github.com/sul-dlss/dlme-transform/blob/main/lib/translation_maps/dlme_collection_from_provider_id.yaml. Each line in this file is a collection and you can link them back to data providers by looking at the prefix in the key e.g. every line that starts with auc- is an AUC collection. There really isn't a great way to get exact numbers of records in each collection. You could query the collection name in DLME which would often be accurate but maybe not always. Is it possible to just make up those numbers for the design?

One thing to point out is American University in Cairo is the most extreme case. They have the most collections. Other providers usually have between 1 and 4 collections. 

I can get you more information as needed. I just need to know a bit more about what you need. I would hate to manually search for each collection to try to get exact numbers of records if its not actually needed. How many data providers would be needed for the design and is it okay to make up the number of records?

**Comment by ggeisler** [comment]
Okay, I think the yaml file is enough for me for design purposes. Exact numbers aren't important, I just want to use realistic data. But I think I can get close enough with this.

**Comment by ggeisler** [comment]
Hmm, maybe I don't understand something here. Our current Statistics page doesn't seem to map very well to the yaml file. For example, the Data Contributors page shows QNL as having 18 collections, but the yaml file seems to only have one entry for QNL ([line 76](https://github.com/sul-dlss/dlme-transform/blob/77b25a8820fa48645f736e1be1af05d33f2c0b3c/lib/translation_maps/dlme_collection_from_provider_id.yaml#L76))

There are other examples but maybe I'm just missing something fundamental?

**Comment by ggeisler** [comment]
Below is one way to expose the collection details for each provider. I've used an expand/collapse approach to exposing the collections because:

- Exposing all the collections directly would make the table considerably longer and visually busy, and
- I'd guess that while many users might find the overall provider stats interesting, they might not care about the collection-level details

So this approach would involve:

- Making the provider table into an accordion (or making the rows function like an accordion)
- Swapping the Items and Collections columns (so that we can place the icon for expand/collapse directly next to the entity -- Collections -- it is exposing)
- Adding the expand/collapse icon to control the visibility of the collections detail section
- Adding the collections detail section for each provider (collection name and collection item count)
- For the provider with only 1 collection case, I've shown the toggle but another option is to omit it in those cases, if the title of the collection isn't important to display here

I don't know how this approach works with the user experience considerations @jacobthill mentions in the third item of the initial issue comment. I think we need more clarity on what the source data for provider collections will look like. In general, though, it's hard to design and develop a feature around data that has a lot of exceptions (e.g., "these are not always proper collections"), so it will help to better understand what those are.

Below are two mockups, but they're both just illustrating how it looks when the user has expanded one provider; I just made one where the expanded provider is in a row with a white background and one where the provider is in a row with a darker background, to make clear how we'd show the provider collections in a vertically expanded row. 

The user could expand more than one row at a time, and the collection names would ideally be links to search results that display the items in that collection. I could fine-tune the visual design a bit if we decide to implement this.

<img width="1062" alt="Screen Shot 2022-01-19 at 4 27 24 PM" src="https://user-images.githubusercontent.com/101482/150234865-9265a96f-956f-4424-a9e6-561ed4b58c34.png">

---

<img width="1062" alt="Screen Shot 2022-01-19 at 4 27 51 PM" src="https://user-images.githubusercontent.com/101482/150234883-31374887-dc3e-48e5-87c4-3fec2ac55c85.png">

**Comment by mwerla** [comment]
@ggeisler Thanks for the design. It looks good to me. A few comments for discussion:
- I think even for a single collections case, the UI should look the same - we shouldn't hide the single collection info, as for most cases the name of the data contributor will be much more general (and less informative) than the collection name.
- I assume we apply  the same approach both to Data Contributors and Item Contributors tables at https://dlmenetwork.org/library/statistics
- Regarding the expand/collapse icon, I am wondering if it would make sense to keep it consistent with the way the hierarchical facet expansion icon will look like (https://github.com/sul-dlss/dlme/issues/1347). So instead if > icon on the left, put [+] icon on the right. This approach would probably allow keeping the Items column as the last one (which I think looks a bit better - very personal opinion).
- Regarding column titles, should we have "Institution/Collections" as the first on in the new design? And btw. I think "Country" will look a bit better than "Countries" in the second column, even though we have a couple of data providers with more than one country.
- Regarding the issue with collections being "not always a proper collection", I think we should try to handle the data in a way that makes the collections meaningful, ideally with the support of the data provider when the connection is established. Jacob's example with a collection that has one item is for me much more a data issue (we do we have it as a collection? how to handle it better) than the UI design issue (how to design for 1 item collections?)

**Comment by jacobthill** [comment]
@ggeisler sorry for the delayed response. Everyone in my house has COVID. In any case, I'm working a few hours today and will try to catch up on Github comments. Regarding the mismatch in collection counts between the current statistics page and the yaml file, the yaml file is accurate; the statistics page can be ignored. The problem comes from the way we currently count collections which is to simply count sub folders for each data provider in the dlme-metadata repo. That worked at first but later we had trouble loading some collections so we broke them into smaller chunks which changed the collection count.

- I agree with @mwerla that we shouldn't change the design for a provider with one collection. 
- To apply the same behavior to Item Contributors we would need to use the yaml file to get the Data Contributor and then use https://github.com/sul-dlss/dlme-transform/blob/main/config/metadata_mapping.json to find the Item Contributor.
- I don't have a preference on which icon is used for expand/collapse
- @mwerla do you have suggestions for how to "handle the data in a way that makes the collections meaningful"? One of the initial requirements was that each collection in DLME have url that we can point to from the collections registry Omeka site. For the collection with only one item, we could not treat it as a collection and still meet that requirement, but we also have several collections with 4 items.

**Comment by mwerla** [comment]
@ggeisler The design looks good to me.

**Comment by thatbudakguy** [comment]
possibly we do the query for collections on the client-side so that we don't hit solr once for every provider.

**Comment by jcoyne** [comment]
I'd suggest using a script like this for accessibility reasons: https://adrianroselli.com/2019/09/table-with-expando-rows.html
