### ISSUE TITLE
Suggest UI design for flagging "bad" records

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/dlme#146]
Perhaps borrowing heavily from Revs?

**Comment by ggeisler** [comment]
Below are mockups for a simple approach, where it doesn't matter if the user is logged in and the user doesn't have the option to find out whether the suggestion she makes is resolved.

(Numbered sections below correspond to the orange numbered icons in the mockups.)

1. Adds  a collapse/expand (e.g., accordion) section above the metadata. Default is closed, so only the section header is shown. 

![flagging-section](https://user-images.githubusercontent.com/101482/29640860-be92f8ca-8815-11e7-9b27-406d4eea018d.png)

2. When the user clicks anywhere in the section header, the section expands to display the form.

![flagging-section-expanded](https://user-images.githubusercontent.com/101482/29641258-9eedc390-8817-11e7-9122-eecf50546354.png)

3. The Submit button sends the form value to the database and/or email address, collapses the section back to the initial state, and displays a flash message to confirm to the user that their suggestion was successfully received:

![flash-message](https://user-images.githubusercontent.com/101482/29641310-d6ef2716-8817-11e7-9598-f754933834ed.png)

4. The Cancel link clears the form input and collapses the section back to the initial state.

Of course, the form could be more sophisticated to help manage incoming suggestions, such as adding a select menu the user would use to add a label classifying the type of metadata problem, etc. but I'm assuming that's beyond the scope of what is needed now.

### Administration
I'm also assuming that for the time being at least, we don't need to create an admin interface for managing incoming suggestions. If we need it, I don't mind mocking something up, but it can get pretty complex so I'll not do it unless necessary. As a general example, though, for Revs we have a dashboard for managing correction submissions (important there, given we've had 97,000 suggestions):

![revs-flagged-items-dashboard](https://user-images.githubusercontent.com/101482/29641500-b9662eaa-8818-11e7-9122-e2da7b2ae9b2.png)

For Revs, while you don't have to be logged in to provide a metadata suggestion, if you are logged in, you have the option to receive an email when your suggestion is resolved. This adds complexity to the submission form, since we need to both offer the email option to the user and give the administrator an associated form to record the resolution:

![revs-resolving-flag](https://user-images.githubusercontent.com/101482/29641534-e64c4bb6-8818-11e7-8a6d-dacc26a37367.png)

**Comment by anarchivist** [comment]
Let's discuss on Thursday's standup?

**Comment by mwerla** [comment]
Looking at the proposed design, we think that the button for reporting corrections could be moved to the side (so that it's well visible, but not presented before metadata). We also think that the message visible when the form is expanded should be more clear. It should encourage the user to report and problems, errors, or comments he/she may have related to the item. The info about general feedback is probably redundant.

**Comment by ggeisler** [comment]
Based on the most recent comments from @jacobthill and @mwerla I think there are several aspects to this ticket that need to be agreed on:

1. Placement of the affordance that opens a feedback form
2. Text used to communicate to the user what the form is for
3. How the submitted form is handled

(There are some more minor things to figure out, such as exact styling, but I don’t think they need discussion at this point.)

## Issue 1: Placement of the affordance that opens a feedback form
Below are mockups exploring options for offering the form on an item show page. All of these involve the same type of affordance (a button that opens a form in place within the page). Another option could be a button that triggers a modal with the form. But in this case I believe a modal could often be frustrating to a user, who has seen something they want to report but after triggering the modal can no longer see or copy the metadata in question because they modal covers it. 

### Option A: Display affordance in smaller column next to the metadata
This seems to be what @mwerla is suggesting, but I see a couple of challenges to this approach:

- When opening the form at tablet or wider viewports, on an item page with a item thumbnail (versus the Mirador viewer), the form will be very narrow. The examples below are at smaller desktop size (tablet will be even narrower, wide desktop a bit wider). I don’t think this will encourage a user to use the form to submit feedback.

<img width="565" alt="Thumbnail - form in sidebar - closed" src="https://user-images.githubusercontent.com/101482/103708193-50c43e80-4f6d-11eb-9173-5e405a87a365.png">

---

<img width="565" alt="Thumbnail - form in sidebar - open" src="https://user-images.githubusercontent.com/101482/103708200-54f05c00-4f6d-11eb-9f00-aac04b598571.png">

- When the [item page uses the Mirador viewer](https://dlmenetwork.org/library/catalog/cambridge_genizah-16780), there is no side column; the page content uses the full-width of the page. So there’s no clear way to use a similar pattern for the feedback affordance on the two variations of the item show page. I think it’s better to use the same pattern for both variations of the page so the user always knows where to expect the feedback affordance.


### Option B: Display affordance centered immediately after the metadata section
Putting the affordance after the metadata section means:

- It will be in the same location for both variations of the item show page
- Because it comes after the metadata it doesn’t interfere with normal browsing of the page
- The form field will be wide enough to be comfortable for the user to input their feedback at all viewports (not great at phone or tablet, but that’s unavoidable)

<img width="565" alt="Thumbnail - form at bottom of metadata - closed" src="https://user-images.githubusercontent.com/101482/103708359-b284a880-4f6d-11eb-99a5-5a13bf53b526.png">

---

<img width="565" alt="Thumbnail - form at bottom of metadata - open" src="https://user-images.githubusercontent.com/101482/103708390-bc0e1080-4f6d-11eb-8d93-100e28430134.png">

---

<img width="565" alt="Mirador viewer - form at bottom of metadata - closed" src="https://user-images.githubusercontent.com/101482/103708408-c6300f00-4f6d-11eb-9874-e5782a6092d4.png">

---

<img width="565" alt="Mirador viewer - form at bottom of metadata - open" src="https://user-images.githubusercontent.com/101482/103708468-e1028380-4f6d-11eb-8a27-ca7d40edae44.png">


The biggest drawback I see to this option is if the item page has a lot of metadata, the user might not see that the feedback affordance exists until they scroll down the page sufficiently. But since discovering and reporting feedback on metadata issues is only something a small percentage of users are likely to do, this seems like only a minor problem to me.

### Option C: Display affordance centered immediately before the metadata section
This option ensures the user will always see the feedback affordance, but I don’t think it really deserves that level of prominence on the page.

<img width="565" alt="Mirador viewer - form at top of metadata" src="https://user-images.githubusercontent.com/101482/103708535-f7104400-4f6d-11eb-965c-204cfe750c80.png">


## Issue 2: Text used to communicate to the user what the form is for
For simplicity, in the mockups I’ve used a very simple text prompt for the form:

> If you see a problem with the metadata for this item, please let us know.

I suppose it could also be something like:

> If you see a problem with the metadata for this item, or have other comments about it, please let us know.

though I'm not clear what you intend to do with comments about an item that aren't actual suggested problems.

@jacobthill’s example of the digitalpasifik.org site seems to indicate he's looking for a more extensive text prompt, but I’m not clear what the goal is, since that example doesn’t really match what I thought this feature was for (metadata corrections versus encouraging users to tell us things about the item that might not be problems that need addressing). Perhaps @jacobthill and @mwerla can suggest the text to use as the prompt for the form, based on your better understanding of what you plan to do with submitted feedback?

## Issue 3: How the submitted form is handled
I assume we want to distinguish submissions of this form from submissions of the general Feedback form. 

- Does this form trigger an email to the same distribution list as the general feedback form, and we simply change the default subject line to help distinguish the two types?
- Or do submissions from this form use another mechanism, such as sending the submissions to a Google spreadsheet?

I believe the email submission would be more straightforward, but again, maybe that decision depends on the workflow  you all have in mind for handling these feedback submissions.

Regardless of where the form data is sent, we’ll obviously show the user a flash message at the top of the page so they know their feedback was successfully received. I’ll mock that up after we make decisions about the bigger issues I outlined above.

**Comment by mwerla** [comment]
Hi @ggeisler!

**Regarding Issue 1**, I like the idea of having the button somewhere on the side, but relatively high on the page. Putting it before the metadata makes an impression that we have a lot of problems with the records, that's why so prominent location. On the other hand, putting it below the metadata, below the page fold line, makes it hard to notice, especially for longer metadata records (in general not so many people scroll down on pages, especially if the content is on top). The style that comes to my mind as a nice solution is to use a side ribbon, just like Hotjar does. You can go to https://www.hotjar.com/ and then (if you don't block some tracking scripts) on the right side of the screen you will see a red "Feedback" ribbon that sticks to the screen position in case of scrolling. Once clicked, it opens a small popup dialog. This approach would work on all variants of the record view.

**Regarding Issue 2**, I've noticed that there is no "Contact" option on the DLME page. There is the "Feedback" button in the header and no contact details in the footer. My suggestion would be to rename the current "Feedback" to "Contact us" (and change the header of the feedback form from "Reporting from: https://dlmenetwork.org/library" to something more encouraging to contact, like for example "To contact us in any matter related to DLME, please use the form below."). 
This rename would allow us to re-use the word "Feedback" in the context of the single record. Then we could make the button label quite short like "Provide feedback about this item", which covers error reporting, comments, etc.

**Regarding Issue 3**, I'd suggest starting with an e-mail with a changed subject line as you propose.  That seems to be the simplest solution, and in case that we start getting too many e-mails, we can think of using some free issue tracking tool that converts e-mails to tasks.

**Comment by ggeisler** [comment]
@mwerla Below are updates on each of the three issues we’ve been discussing in this ticket. I’ll discuss them in reverse order so the simplest are first.

## Issue 3 - Mechanism for submitting item detail page feedback
We agree we’ll use the same approach as with the general site feedback link: the form generates an email to the Configuration > General, Basic settings, Feedback recipients or whoever is currently getting feedback emails (I’m  a bit unclear on this because on -prod the only recipient that has validated is Wayne at CLIR and I assume more people than him are getting feedback emails?)

We want to use a different subject line for the email, however, so it will be easier to sort out metadata/detail page specific feedback from feedback sent via the general site feedback form. I’ll suggest:

> DLME item feedback

But @mwerla and/or @jacobthill feel free to suggest something that makes more sense to you.

The body of the mail could be exactly the same as with the general site feedback email, I believe.


## Issue 2 - Updating the exhibit feedback link and associated form
I’ve created a separate ticket for this: https://github.com/sul-dlss/dlme/issues/1116

Please make any comments or suggestions on this aspect of things there.


## Issue 1 - Item show page feedback affordance and associated form

We took a look at your suggested example at hotjar.com and we think we understand your general goal. My mockup below is a variation on that, with the goal of a solution that addresses your general concern without adding a completely new pattern that doesn’t exist in Spotlight or the Bootstrap framework it uses (which would add to the time needed to complete this feature). I will defer to @mejackreed to address any concerns about the technical complexity of this proposed solution or suggestions you might have that would increase the complexity.

(There's an interactive mockup of what I discuss below at: https://xd.adobe.com/view/96370c32-60f1-4d1c-bfee-5eead2b2f5a5-c364/?fullscreen

The clickable elements are the Feedback button (on the first page), the Close and Submit buttons in the modal, and the flash message on the third page.)

### Feedback affordance
The proposal is to add a vertically-oriented button to the right-edge of the item details page:

<img width="1130" alt="Thumbnail - Feedback button " src="https://user-images.githubusercontent.com/101482/104664474-916a3900-568c-11eb-9755-7f1d4522fb0e.png">

---

- Button label is `Feedback`
- Button is fixed in place, on the right edge of the page, in the vertical center of the page. By fixed in place, I mean as the page is scrolled the button stays in place rather than scrolling with the page (same as hotjar).
- Button is styled just like a primary button elsewhere in the app, though I think we might want to use the `btn-sm` size.
- The Feedback button should be last in the tab order on the page (though as a separate issue we might need to look at keyboard access to this page because I’m not seeing expected results)
- Selecting the Feedback button triggers a modal with the feedback form (covered in the next section)

Here's how the button looks on the other (Mirador) variation of the item detail page:

<img width="778" alt="Mirador - feedback button" src="https://user-images.githubusercontent.com/101482/104664591-db531f00-568c-11eb-9ec3-52732094b227.png">

---


### Feedback form
The feedback form is presented in a modal:

<img width="1130" alt="Thumbnail - modal" src="https://user-images.githubusercontent.com/101482/104664603-e443f080-568c-11eb-9d86-d18c2b916825.png">

---

I think the demo modal here: https://getbootstrap.com/docs/4.4/components/modal/#live-demo is basically what I’m suggesting. We want to display it close to the top of the page to better increase the chances that it doesn’t cover the metadata on the page, since that is what the user is presumably commented on, and they might need to reference it as they fill out the form.

We should use the version that allows the user to close the form by clicking anywhere off of it, in addition to using either of the close buttons, since some users may just open it out of curiosity and we should make it as easy to dismiss as possible.

For the instructions text on the form, I mocked up:

> Provide feedback about this item:

@mwerla and/or @jacobthill I think you are in a better position to provide final instructions text for the form if you think this is too simple. I’m not entirely sure what you are expecting users to provide here so it’s hard for me to know what the best text is.

### Upon form submission
For the user, we should display a flash message if the form is successfully submitted:

<img width="1130" alt="Thumbnail - flash message" src="https://user-images.githubusercontent.com/101482/104664666-0e95ae00-568d-11eb-8b43-c36a652f8910.png">

---

> Your feedback has been submitted. Thank you.

Again, suggest different wording if you think there is something more or different we should tell users.

As noted in the Issue 3 section above, the submitted form should trigger an email with the page URL and the form field information to the appropriate recipients.

**Comment by mwerla** [comment]
Regarding issue 3 and 2: 
- @ggeisler All looks good to me. 
- @jacobthill Please verify who is getting the feedback from DLME. For some reason, I thought that it goes to some mailing list where QNL was supposed to be added as well.

**Comment by mwerla** [comment]
@ggeisler Regarding Issue 1, I like the proposed design and I have the following suggestions:
1) I think that the proposed feedback form can be used in two main cases: (a) negative feedback about the item or (b) inquiry about the item. I think it would be good to clarify the inquiry possibility in the form leading text. For example: "If you have any questions or comments regarding this item, please let us know using the form below.". It's a bit longer, but more straightforward regarding what is expected.
2) The form should consist of 2 fields: mandatory feedback text area and optional text input for e-mail address of the submitter (the feedback may require response/clarifications).
3) Regarding the submission confirmation message, I propose to add a clear "next step" message, like: "Your feedback has been submitted. Thank you. We will take care of it as soon as possible."

**Comment by ggeisler** [comment]
@mwerla Thanks for the text suggestions, they make sense to me.

Below is the final design for the team to work from. This incorporates your suggestions but if you see any issue let us know, otherwise we'll assume it is ready to work on.

## Feedback affordance
The proposal is to add a vertically-oriented button to the right-edge of the item details page:

<img width="1130" alt="Thumbnail - Feedback button " src="https://user-images.githubusercontent.com/101482/104664474-916a3900-568c-11eb-9755-7f1d4522fb0e.png">

---

- Button label is `Feedback`
- Button is fixed in place, on the right edge of the page, in the vertical center of the page. By fixed in place, I mean as the page is scrolled the button stays in place rather than scrolling with the page (same as hotjar).
- Button is styled just like a primary button elsewhere in the app, though I think we might want to use the `btn-sm` size.
- The Feedback button should be last in the tab order on the page 
- Selecting the Feedback button triggers a modal with the feedback form (covered in the next section)

Here's how the button looks on the other (Mirador) variation of the item detail page:

<img width="778" alt="Mirador - feedback button" src="https://user-images.githubusercontent.com/101482/104664591-db531f00-568c-11eb-9ec3-52732094b227.png">

---

## Feedback form
Selecting the Feedback button triggers a modal with the feedback form:

<img width="1126" alt="modal-thumbnail" src="https://user-images.githubusercontent.com/101482/105107156-aec84a00-5a74-11eb-88a4-ab0013d5d99b.png">

---

I think the demo modal here: https://getbootstrap.com/docs/4.4/components/modal/#live-demo is basically what I’m suggesting. We want to display it close to the top of the page to better increase the chances that it doesn’t cover the metadata on the page, since that is what the user is presumably commented on, and they might need to reference it as they fill out the form.

We should use the version that allows the user to close the form by clicking anywhere off of it, in addition to using either of the close buttons, since some users may just open it out of curiosity and we should make it as easy to dismiss as possible.

For the instructions text on the form:

> If you have any questions or comments regarding this item, please let us know using the form below.

Label for the first field, a textarea (`rows="4"`):

> Question or comment

Label for second form field, an input:

> Email address (optional) 

## Upon form submission
For the user, we should display a flash message if the form is successfully submitted:

<img width="1126" alt="flash-message" src="https://user-images.githubusercontent.com/101482/105107481-783eff00-5a75-11eb-82e0-ad60c384be49.png">

---

> Your feedback has been submitted. Thank you. We will take care of it as soon as possible.


## Resulting email
The email that is triggered when the user submits the form can work almost exactly like the regular site feedback. We want to use a different subject line for the email, however:

>   DLME item feedback

The body of the mail could be similar to the same as with the general site feedback email, I believe, but should also include the user's email address, if provided.

**Comment by mwerla** [comment]
@ggeisler Looks great to me, thanks!

**Comment by ggeisler** [comment]
@asmaaalkuwari For this feature I think we'll need Arabic translations for:

> If you have any questions or comments regarding this item, please let us know using the form below.

> Question or comment

> Email address (optional)

> Your feedback has been submitted. Thank you. We will take care of it as soon as possible.

**Comment by mejackreed** [comment]
In Arabic view, Button on right, with Arabic text starting from bottom going up.

**Comment by mwerla** [comment]
Tested English version on dev, looks ok to me.

**Comment by mwerla** [comment]
@asmaaalkuwari Please check the Arabic version

**Comment by asmaaalkuwari** [comment]
@mwerla arabic is working fine and translations are correct

**Comment by jacobthill** [comment]
@asmaaalkuwari the Arabic translations are missing. I think you must have checked the "Contact us" form at the top. We need translations for the record "feedback" form
<img width="849" alt="Screen Shot 2021-02-03 at 6 29 31 AM" src="https://user-images.githubusercontent.com/37662787/106741171-5737eb80-65e9-11eb-9d7e-0027f55fc9a9.png">
