### ISSUE TITLE
Remove references to s3 bucket for carrierwave storage

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/dlme#1659]
We can delete https://github.com/sul-dlss/dlme/blob/main/config/initializers/carrierwave.rb
And remove https://github.com/sul-dlss/dlme/blob/90e66d6075c8c3aaa0db2a8d41d2bf2b02de9554/config/initializers/riiif.rb#L2-L10
And remove https://github.com/sul-dlss/dlme/blob/90e66d6075c8c3aaa0db2a8d41d2bf2b02de9554/config/settings.yml#L24-L25

Since we're no longer using s3 for featured image storage (#1614). This shouldn't change any behavior since we're already setting the config value to `nil`, it's just removing effectively dead code.

**Comment by hudajkhan** [comment]
We may be able to delete https://github.com/sul-dlss/dlme/blob/main/config/initializers/riiif.rb as well because, after the deletion of the S3 relevant block, the code looks identical to https://github.com/projectblacklight/spotlight/blob/main/lib/generators/spotlight/templates/config/initializers/riiif.rb.
