### ISSUE TITLE
Trying to "Fetch by URL" with an incorrect file path triggers the "JSON contained duplicate identifiers" error message

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#1704]
Make sure the duplicate id test accounts for missing files and ideally add a new test to check for incorrect file paths.

**Comment by corylown** [comment]
The validity check on uploaded files can fail for a variety of reasons: https://github.com/sul-dlss/dlme/blob/main/app/services/ndjson_upload.rb#L12

If the validity check finds a problem the error message displayed can be misleading depending on the cause of the failure: https://github.com/sul-dlss/dlme/blob/main/config/locales/en.yml#L51

**Comment by thatbudakguy** [comment]
I think this results from the refactor that I did a bit ago to add the API version of this endpoint, which has some associated error handling. The issue is that the non-API version didn't have any specific error handling other than the duplicate identifier detection, so after the refactor, all errors get treated as that, because there aren't any code paths to throw any other kind of error there.

Probably we just need to borrow https://github.com/sul-dlss/dlme/blob/8b0f2f9307d967659192d9d5c38717dcc93138a0/app/controllers/api/harvests_controller.rb#L22-L49 and adapt to this controller, and also copy the corresponding tests from the API controller and adapt those.

**Comment by thatbudakguy** [comment]
(you could even extract `handle_error` and `current_exhibit` to a concern if you wanted, since that behavior will now be shared between the two controllers)

**Comment by hudajkhan** [comment]
As @thatbudakguy indicated, better handling of the error itself would resolve this situation. Just documenting the current code path below: 
https://github.com/sul-dlss/dlme/blob/main/app/controllers/harvests_controller.rb#L14 shows the call to Ndjsonupload.  Ndjsonupload (https://github.com/sul-dlss/dlme/blob/main/app/services/ndjson_upload.rb#L12)  returns three errors which all match the API controller options above: :no_url, :file_not_found, and :duplicate_ids.  Currently, if the upload method returns any error, the code goes to the invalid_file method https://github.com/sul-dlss/dlme/blob/main/app/controllers/harvests_controller.rb#L24 which uses "dlme_s3s.form.error" as the main go to error (which is the JSON duplicate identifier error).

**Comment by hudajkhan** [comment]
For the moment, not integrating handling for the API and this admin UI harvest code into the same concern.  There may be some refactoring that could be done in that context perhaps separately.
