### ISSUE TITLE
undefined method `to_str' for Array

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dlme#1705]
https://github.com/projectblacklight/spotlight/blob/76a2b437f1e34854cf4bde43625089d4c2a14e96/app/controllers/concerns/spotlight/base.rb#L36

```
NoMethodError: [1mundefined method `to_str' for ["A Football Match"]:Array ([1;4mNoMethodError[m[1m)[m

[1m        title: CGI.unescapeHTML(view_context.document_presenter(doc).heading.to_str),[m
[1m                                                                            ^^^^^^^[m
[1mDid you mean?  to_set[m
[1m               to_s[m
```

This should already be returning a string per the Blacklight docs: https://github.com/projectblacklight/blacklight/blob/main/app/presenters/blacklight/document_presenter.rb#L45

**Comment by thatbudakguy** [comment]
Might need some help from @cbeer to figure out how to address this.

**Comment by hudajkhan** [comment]
I have put my name on this just to take a look but feel free to add yourselves : )

**Comment by hudajkhan** [comment]
When using autocomplete, the code searches for Solr documents whose titles (as specified in configuration in catalog controller for title field) match the input.  Eventually, the code executes the Document Presenter heading function, which returns an array of values instead of a single value as expected, leading to this error. 

So far, I've been comparing vanilla Spotlight to DLME to see the differences.  
a) When I compile, Spotlight ends up using Blacklight 7.3.3.1.  DLME is using Blacklight 8 beta 8.
b) The code uses the Show presenter, which then goes to the Blacklight Document Presenter and uses its heading method.  Eventually this means FieldPresenter and FieldRetriever are used (the former calls the latter to get the values for the field). 
c) It seemed to me that field values are always returned in an array because of https://github.com/projectblacklight/blacklight/blob/main/spec/presenters/blacklight/document_presenter_spec.rb#L32 but the presenter must have handling to return a single value, because: https://github.com/projectblacklight/blacklight/blob/main/spec/presenters/blacklight/document_presenter_spec.rb#L32 . (Need more info on this part). 
d) DLME has its own custom Show presenter but it just seems to be including DLME's thumbnail presenter and I'm not sure I see anything else being overridden (at the moment).  
e) Vanilla spotlight doesn't have a view configuration specified for the index title field.  DLME uses the Display Field Blacklight configuration and a multi-language related lambda.  I tried removing the lambda and still found the same error with the heading values being returned as an array. 
f) Because of (e) above, the DLME code returns the response from https://github.com/projectblacklight/blacklight/blob/main/app/presenters/blacklight/document_presenter.rb#L47 which returns an array.  Vanilla spotlight with no view config goes the other route and returns https://github.com/projectblacklight/blacklight/blob/main/app/presenters/blacklight/document_presenter.rb#L51 .

I still don't know why I'm seeing an array in one and not the other, and agree with @thatbudakguy that eventually I'll have to ask @cbeer   : )

**Comment by hudajkhan** [comment]
Also the component in use is the Blacklight::MetadataFieldComponent, and the code ends up using Blacklight::FieldPresenter.

**Comment by hudajkhan** [comment]
- When vanilla Spotlight sees the title field, the values from the Solr document are stored in an array.  When the heading method is executed and FieldPresenter retrieves the values to return for this request, the values from Solr are processed through the Pipeline (details below). In vanilla Blacklight, the values are converted to a string here https://github.com/projectblacklight/blacklight/blob/main/app/presenters/blacklight/rendering/join.rb#L6 in the render method (i.e. the "values.to_sentence" portions).  In contrast, DLME has its own set of Pipeline operations, and its own join code (https://github.com/sul-dlss/dlme/blob/main/app/processors/join.rb#L7) which does not do a safe_join operation on the values array when the request is coming from a Catalog Controller and is asking for JSON.   The autocomplete code fits both of these criteria, so this join code https://github.com/sul-dlss/dlme/blob/main/app/processors/join.rb#L8 returns the original array instead of a string representation, which eventually leads to the to_str error.
- The MultilingualLocaleAwareField (https://github.com/sul-dlss/dlme/blob/main/app/controllers/concerns/multilingual_locale_aware_field.rb) extension is called since the lambda function is passed to the DisplayField configuration for the index title field: https://github.com/sul-dlss/dlme/blob/main/app/controllers/catalog_controller.rb#L69 .  Note the catalog controller passes in a "first" option.  This line seems to be checking that "first" option https://github.com/sul-dlss/dlme/blob/main/app/controllers/concerns/multilingual_locale_aware_field.rb#L35, but "values.find(&:any?)" still returns an array and not a string.


More reference information below: 
- The Blacklight FieldPresenter uses the Rendering Pipeline (which consists of a series of classes that do specific actions with the values returned for the field) as shown here: (https://github.com/projectblacklight/blacklight/blob/main/app/presenters/blacklight/field_presenter.rb#L38) and here: https://github.com/projectblacklight/blacklight/blob/main/app/presenters/blacklight/field_presenter.rb#L70 .

- The Pipeline operations for DLME are specified here https://github.com/sul-dlss/dlme/blob/main/config/initializers/blacklight.rb .   The pipeline operations list for DLME is Blacklight::Rendering::HelperMethod, Blacklight::Rendering::LinkToFacet, Blacklight::Rendering::Microdata, Autolink, BidiWrap, Paragraph, Join, Collapse .  This list is different from the default Blacklight list of operations defined here https://github.com/projectblacklight/blacklight/blob/main/app/presenters/blacklight/rendering/pipeline.rb#L12  .  Of note, FieldPresenter takes HelperMethod out of the list of operations https://github.com/projectblacklight/blacklight/blob/main/app/presenters/blacklight/field_presenter.rb#L29 so the default Blacklight list is operations for FieldPresenter is Blacklight::Rendering::LinkToFacet, Blacklight::Rendering::Microdata, and Blacklight::Rendering::Join.

**Comment by hudajkhan** [comment]
When I commented out this line https://github.com/sul-dlss/dlme/blob/main/app/processors/join.rb#L8, the error went away and the autocomplete worked, but the logic to prevent the values array from having a join operation was added specifically to prevent a catalog controller JSON request from joining the values into a string.  If the field configuration "first" option is supposed to only return the first element as a string, MultilingualLocaleAwareField could be updated?  Within catalog controller, the "first" option is only used twice and both times with MultilingualLocaleAwareField.  Another option is to reconsider the join code and enable that to return a string in this particular case (perhaps using yet another option to be passed through the config).

**Comment by hudajkhan** [comment]
Another possibility may be to join the array at the autocomplete step itself? That is closest to the requirement for a string. i.e. https://github.com/projectblacklight/spotlight/blob/main/app/controllers/concerns/spotlight/base.rb#L36 
(Retrieve "view_context.document_presenter(doc).heading". Check if it is an array.  Do a join.  Return string.)

**Comment by hudajkhan** [comment]
@cbeer agrees it seems reasonable to try updating Spotlight as per the comment above. I will create a separate pull request.

**Comment by hudajkhan** [comment]
Separate Spotlight pull request is here: https://github.com/projectblacklight/spotlight/pull/2971

**Comment by hudajkhan** [comment]
I closed that one and now have this one: https://github.com/sul-dlss/dlme/pull/1759 . Thanks to @jcoyne for suggestions.
