### ISSUE TITLE
Investigate how to load data in prod safely

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#1758]
The current data mapping workflow is done via either airflow or locally. In either case, the IR file is loaded into the stage_data_share drive, indexed in stage, reviewed and then we need a way of loading the reviewed data in prod.

**Comment by jcoyne** [comment]
It sounds to me like you need a separate production environment to do data development in.  "Stage" for the development team is a place to test code and we don't treat it with the assurances you need in order to do data development.

**Comment by jacobthill** [comment]
Yeah, we need to talk this through with @aaron-collier. There are concerns with having a parallel production etl environment that loads directly to prod. We need to consider the possibility of copying approved data from stage to prod.

**Comment by thatbudakguy** [comment]
Steps identified during meeting today to support this:

- Ask Ops for a new "prod review" environment, specced the same as current production
- Configure automated deployment to prod-review on release (same as prod)
- Unmount the current datashare volume from stage
- Remount the current datashare volume to both prod-review and prod
- Change airflow to hit the /harvest API endpoint on prod-review (instead of stage)
- Update relevant documentation

Closing this ticket in favor of breaking these out to separate tasks.
