### ISSUE TITLE
Evaluate viability of Traject reader classes for FGDC and MODS

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/dlme#21]
Requires at least a minimum viable mapping for each format

**Comment by cmh2166** [comment]
[WIP]

For MODS, to create a MODSreader class in traject, seeing that we'd need to create the following (based loosely on the marc equivalents; i think we can massively simplify a lot of this, esp. using `sul-dlss/mods` gem):

- [ ]  `macros/mods.rb` : methods for pulling full MODS out, serializing again if needed, some basic string trimming 
- [ ] `macros/mods_semantics.rb` : this is first imported / call by `Traject::Indexer#load_config_file`, and gives us to certain MODS fields. Seems like it replicates `sul-dlss/mods` gem functions.
- [ ] `mods_extractor_spec.rb` : I think this is just about parsing field requests, and is especially complicated in the MARC because of control fields / data fields splits, fields, subfields, tags, etc. 

(will continue, pulled into meeting)

**Comment by cmh2166** [comment]
Okay to close as we're implementing these mappings now? Open new issues on writing up reports for better approach in the future, data pipeline considerations, etc.

**Comment by cbeer** [comment]
👍
