### ISSUE TITLE
Make "Exhibit dashboard" accessible from all pages

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#492]
`Exhibit dashboard` in `spotlight.stage.dlmenetwork.org` is only accessible from the home page. If you are on `Site administration` and click the drop down menu `Exhibit dashboard` is not there. The dropdown menu should be consistent throughout.

**Comment by justinlittman** [comment]
Let's discuss this a bit. Exhibit dashboard is only available when you're in an exhibit. (In the case of DLME there is only one exhibit.) When you're in Site Admin, you're not within an exhibit, so it is not available.

Wondering whether Transform data should be under Exhibit config rather than Site Admin? Let's discuss.

**Comment by justinlittman** [comment]
Proposed approach is to add a new menu item for Transform data. Therefore, depends on #469.
