### ISSUE TITLE
Add bulk tagging feature to admin panel

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#533]
Need the ability to identify a set/subset of records and tag them with the same subject tag. For example, select a collection (e.g. a folder) and tag all items.

**Comment by ggeisler** [comment]
I think we should keep this ticket open so we represent the need for this feature in DLME but I do want to note that this feature would be useful for Spotlight in general (it's been discussed for several years), so if and when we get to it, we probably would want to do in the Spotlight codebase versus DLME: https://github.com/projectblacklight/spotlight/issues/1439

**Comment by jacobthill** [comment]
@ggeisler, @caaster One question I have about this feature is weather or not we could make it possible to add and remove items individually e.g. If I want to make a "Medicine" category and I search "Medicine" I may get many items that are related to medicine and some that aren't. Can I tag all of them and then remove the tag from only the ones that aren't about medicine? Similarly, would it be possible to add a single record to an existing category (e.g. a button from the record view). These features could give curators a lot more flexibility to create rich collections. I assume they would need to be ticketed separately but this seemed like a good place to have this discussion prior to creating new tickets.

**Comment by ggeisler** [comment]
@jacobthill I think the general answer to your questions is Yes, though keep in mind I haven't started design on this so nothing is guaranteed until we get to the design and implementation details and see what is really feasible.

But my preliminary idea is that bulk tagging will show a list of items you've gathered in some way (created a search result manually, or using an existing browse category) and each item in the list will have a checkbox. There will also be a global checkbox that can turn on/off all the individual item checkboxes at once. So you could select all your items with the global checkbox and then uncheck the items you don't want included, and then apply a new tag to everything that is still checked.

You can already manage item tags on the item detail page. You can add a tag or remove a tag. So if, for instance you've created a browse category based on a tag, you can go to any individual item detail page, select Edit, and add that tag to it. And then that item will be part of the browse category based on that tag.

**Comment by jacobthill** [comment]
@ggeisler, I believe this has been implemented and can now be closed. Is that correct?

**Comment by ggeisler** [comment]
@jacobthill Maybe? Spotlight now has two approaches to bulk tagging:

- Add and remove tags through the exhibit UI
- Add and remove tags by downloading/uploading a spreadsheet through the admin UI

### Add and remove tags through the exhibit UI

Available now in DLME. Note that the Bulk actions affordance is not available for browse category results, just search results generated by using some combination of facets and search terms (so you could still get the same results as a browse category, you'd just have to generate it by hand):

<img width="1129" alt="Screen Shot 2021-07-12 at 9 19 34 AM" src="https://user-images.githubusercontent.com/101482/125323012-32137b80-e2f3-11eb-9872-f7a055e78c56.png">

### Add and remove tags through a spreadsheet via the admin UI

This is available in Spotlight but not DLME. I don't remember if there is a specific reason for this, or if we were just waiting to a future workcycle to add it to DLME.

#### Spotlight
<img width="509" alt="Screen Shot 2021-07-12 at 9 18 57 AM" src="https://user-images.githubusercontent.com/101482/125323337-84549c80-e2f3-11eb-8b3b-d918220fc973.png">


#### DLME
<img width="397" alt="Screen Shot 2021-07-12 at 9 20 19 AM" src="https://user-images.githubusercontent.com/101482/125323384-920a2200-e2f3-11eb-8ddd-c8b4d35d409b.png">

---

So maybe you can close this ticket and if you think we need to add the spreadsheet option to DLME, create a new ticket specifically about that, and if the developers know of a reason we couldn't do that for DLME that I don't recall, they can tell us there. (Though I think it might just be because we implemented it after the DLME workcycle and it requires custom work beyond just updating DLME to the latest Spotlight version.)

**Comment by jacobthill** [comment]
Thanks
