### ISSUE TITLE
Create view for mixed language metadata

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#589]
Some records will have metadata that is all English ([example](https://spotlight.stage.dlmenetwork.org/library/catalog/ans_2010-44-2)). Some records will have modern Turkish (e.g. Turkish in Latin script) or French, etc. and English ([example](https://spotlight.stage.dlmenetwork.org/library/catalog/oai:cdm21044.contentdm.oclc.org:emirgan%2F925)). Some records will have Arabic and English ([example one](https://spotlight.stage.dlmenetwork.org/library/catalog/010740758), [example two](https://spotlight.stage.dlmenetwork.org/library/catalog/b17704236), [example three](https://spotlight.stage.dlmenetwork.org/library/catalog/oai:cdm15795.contentdm.oclc.org:p15795coll19%2F28)). Eventually, some records will have all Arabic metadata but we don't have an example until QNL updates their metadata. We need a view that will handle these use cases and the problems they pose, including right-to-left and left-to-right languages in the same record. 

The cases with Arabic and English mixed will be among the most challenging. Some of the fields will have Arabic and English for every record (agg_provider => agg_provider_ar, agg_data_provider => agg_data_provider_ar, cho_edm_type => cho_edm_type_ar, cho_has_type => cho_has_type_ar, cho_language => cho_language_ar, cho_date_range_norm => cho_date_range_norm_ar). Some fields could come in either or both languages (titles, contributors, creators, and descriptions are good examples).  When in the Arabic view, Arabic values should be displayed and English equivalents should be suppressed. English values with no Arabic equivalent should still be displayed alongside the Arabic however. The opposite is true as well. When in the English view, English values should be displayed and Arabic equivalents should be suppressed. Arabic values with no English equivalent should still be displayed alongside the English. This is one possible solution though it might be complicated to implement. Another option would be to display all values in the metadata but put the Arabic to the right and the English on the same line to the left (e.g. two columns). This would be easier to implement but we need to determine if it is visually appealing.

**Comment by ggeisler** [comment]
Below is a proposed strategy for how to determine which language-versions of metadata values to display on item show pages when the user is in English and Arabic locales. @jacobthill and I discussed this but I revised the mockups after our discussion so @jacobthill please review and let me know if you see any problems.

Some general notes:
- I think we will want to use the same strategy for result item metadata but that might be a separate issue to look at later.
- My mockup examples are contrived so that I could express the different possible metadata language possibilities in a single example. @jacobthill and I can work on providing pointers to actual records that express specific scenarios if necessary.
- Don't assume any Arabic text is accurate; I had a lot of problems working with Arabic text (copying and pasting, editing, etc.) in my mockup tool and just used Google Translate for field names. @jacobthill will be providing us with real Arabic field names later.

### General strategy for determining which language values to display
I believe we settled on a fairly straightforward strategy:

**A.** If a metadata value is available in the same language as the current locale (e.g., `{"en": ...}` when user is in the English locale), display the `"en"` value and ignore any other language versions of the value for that metadata field. This is the case marked with an "A" in my mockup examples below.

**B.** If a metadata value is **not** available in the same language as the current locale (no `{"en": ...}` value when the user is in the English locale), display **all** language versions of that metadata field value, with the following prioritization to determine the order of display:

**B1.** If an Arabic value exists for the field, display that value first. (English value first if in Arabic locale.)
**B2**. If a `"none"` value exists for the field, display that value next.
**B3.** If there is no English and no Arabic value, display the `"none"` value first.
**B4.** If there is no English value, no Arabic value, and no `"none"` value, display any other values in the order found.

### Example of a show page in English locale
The metadata in the mockup below is what we want to display, given the source data. The callouts correspond to the A and B cases above.

**A** - Date, DC Rights, Type, and Provider/Source Institution all show just an English value, because we are in the English locale and those fields have an `"en"` value. Other language values that exist are ignored (e.g., the `"tr"` value for Type).

**B1** - We're in the English locale but there is no `"en"` value for Description. There is an "ar" value, though, so we display that.

**B2** - We're in the English locale but there is no `"en"` value for Creator, but is there an "ar" value so we display that. There is also a "none" value so we display that next, followed by the remaining language values, which is just the "tr" value in this case (but could be others, all of which would be displayed).

**B3** - For Title there is neither an English nor an Arabic value, but there is a "none" so we display that. It's not the case here, but if there were other language values, they would be displayed next.

**B4** - I didn't put an example of this in the mockup, but if there were a field with no "en", "ar", or "none" but other language values, they would all be displayed, in the order found.

<img width="1160" alt="Screen Shot 2019-11-08 at 10 41 54 AM" src="https://user-images.githubusercontent.com/101482/68502147-fb7f8680-021c-11ea-9c47-4e4afad049d7.png">

### Example of a show page in Arabic locale
**A** - We're in the Arabic locale and Description, Creator, and Provider/Source Institution all have "ar" values so we use those and ignore any other language values that might exist for those fields.

**B1** - Date, Rights, and Type don't have "ar" values but do have "en" values so we display those first. That's all we have for Date and Rights, but Type also has a "tr" value so we also display that.

**B3** - For Title there is neither an English nor an Arabic value, but there is a "none" so we display that. 

<img width="1160" alt="Screen Shot 2019-11-08 at 11 46 22 AM" src="https://user-images.githubusercontent.com/101482/68503292-bad53c80-021f-11ea-9e88-eefcc45486b8.png">

### Show page title
I included the Title field in the metadata of my mockups to show we want to follow the same strategy for that field if we include it in the metadata but I'll note that we could get into some unpleasant display issues if we use this strategy for displaying the Title value in the show page title (the `<h1>`). If there are multiple values for title but none match the current locale, our strategy says we should display all of those language versions. That could make the page title take up a lot of vertical space and look odd.

Perhaps we use the same basic strategy (first try to find a value matching the current locale, next try match the other primary lang ("en" or "ar"), next try to match "none") but only use the first match for the page title, and assume the user can see any other language versions of the title in the metadata.

We're not even sure at the moment how often this case would come up for the title field, though.

**Comment by cbeer** [comment]
Thanks @ggeisler ; it looks like the IR makes a distinction between Arabic in Arabic script and Arabic in latin script (and likewise for Turkish and Farsi). Are we making any such distinction in the UI, or just going  off the top level language code?

**Comment by ggeisler** [comment]
@cbeer: I don't think the secondary-level code would affect the philosophy behind our proposed strategy, so I'd say just stick with using the top-level language code, but perhaps @jacobthill has more thoughts on this?

The secondary-level code might be useful for determining whether we displaying the value using the Arabic font or not, but I think that's a different issue.

I honestly have not seen enough examples of different metadata values to confidently understand the implications of the proposed strategy, but am hoping after we get a first-pass done we can spend time looking at the results and decide on any adjusments or refinements needed.

**Comment by caaster** [comment]
@cbeer @ggeisler I've recently asked @jacobthill for more information about this ticket, as I thought I understood there was lingering confusion, especially more information needed from Jacob. Here is Jacob's response:

I'm not positive what information you are looking for or why it will be used so its unclear how I should write a ticket. Here is what I have:

All records will have Arabic and English metadata fields for: cho_edm_type, add_provider, agg_provider_country, agg_data_provider, agg_data_provider_country
Whenever a record has a cho_language value at all, it will have one in English and Arabic at minimum. This is a normalized field so once we have one, we map it to the other. If the value in the incoming data is in a language other than English or Arabic (such as Sakip Sabanci in Turkish) it will have that language plus English and Arabic. 

cho_has_type is not always possible to map but when it is available, it will be always available in Arabic and English only. 

Everything else is whatever the provider gives us. In some cases this is mixed, occasionally with the same field in both languages (e.g. title in Arabic and English). Often it will have Arabic in some fields and English in others (such as AUB). For QNL we will eventually have all fields in both languages. 

I'm not sure that is what you are looking for. Its also important to note that we have to design the application in a way that metadata in new languages doesn't break it (e.g. a case that catches anything other than Arabic or English instead of a case that catches French, another that catches Turkish, etc. that will break when we get metadata in German). I hope I am on the right track with what you are looking for. If not, please let me know.

**Comment by caaster** [comment]
@jacobthill - fyi @cbeer & @ggeisler & I met this morning to make sure we're on the same page regarding this ticket. We are, and so I'm sharing some clarifying information (and this ticket should stay closed -- although additional questions are most welcome if you have them).

1. The application has been designed in such a way that adding new languages does not break it. It does require that each time a new language is added, the following changes must be made:
a. Whatever work needs to happen with the transform code -- that involves indicating a new language -- needs to be done. (I am not articulating this with specifics because we're uncertain of the exact nature of your work in this regard.)
b. After you've added a new language to the transform code, you will need to add a new language code to the list of acceptable_bcp47_codes here: https://github.com/sul-dlss/dlme/blob/master/config/settings.yml#L32-L39 

2. On a related but different note, **for the following fields**, when you are in the Arabic locale you will only see the Arabic values displayed, and when you are in the English locale you will only see the English values displayed: 
cho_edm_type
add_provider
agg_provider_country
agg_data_provider
agg_data_provider_country
cho_language
cho_has_type
For all other fields, regardless of locale, you will see all values displayed regardless of language.
