### ISSUE TITLE
Style issues with Arabic date slider view

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#777]
Right to left conversion issues in date range slider.

- minus sign is to the right of the number instead of left
- numbers pushed off the screen 

Could possibly be solved by using the English slider since numbers go left to right in Arabic.

<img width="238" alt="Screen Shot 2019-12-05 at 2 25 44 PM" src="https://user-images.githubusercontent.com/37662787/70267120-c73fad00-176b-11ea-8def-48c84351152e.png">

**Comment by ggeisler** [comment]
As some of us discussed in a meeting the other day, if technically feasible, I'd prefer to just use the LTR version of the date slider and associated elements when in Arabic.

So the goal is to still show the facet labels RTL when in Arabic, but the contents of the date slider panels themselves can be LTR. The text labels should be in Arabic but otherwise the panels would be the same as when looking at them using the English locale.
