### ISSUE TITLE
Arabic metadata values display in English view when English available

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#780]
When the English value is available (e.g. for `Language` and `Type (primary)`) the Arabic equivalent should not display in the English view. Is this something that needs to be configured via the admin view?

<img width="846" alt="Screen Shot 2019-12-06 at 10 51 28 AM" src="https://user-images.githubusercontent.com/37662787/70336070-8355b200-1816-11ea-8487-d1c2197642f4.png">

**Comment by cbeer** [comment]
Can you provide  a link to this particular record?

**Comment by ggeisler** [comment]
This is not a admin UI configuration thing.

I agree that Type (primary) should only show English when in the English locale (I believe this also can occur with Type (secondary): https://spotlight.dev.dlmenetwork.org/library/catalog/met_323126).

But for Language, isn't that a multi-valued field where we are telling the user all the languages that are part of this record, in which case we do want to display all values? Or maybe I'm misunderstanding this field.

**Comment by ggeisler** [comment]
FWIW, as I discussed with @jacobthill yesterday, I'm hoping we will hide "Type (primary)" and "Type (secondary)" eventually, if we can determine that "Object type" is always present if there is a "Type (primary)" value (since Object type encompasses the values of the other two fields).

**Comment by cbeer** [comment]
Thanks @ggeisler, I was about to ask the same thing. I assumed we didn't apply the multilingual-ness to that field because it was going away. The object type is made up of data from the primary + secondary fields, so should always be present (unless there's a mapping issue?)

**Comment by jacobthill** [comment]
Here is a link to a different record with the same problem: https://spotlight.dev.dlmenetwork.org/library/catalog/8c8aa7f4-abd5-4342-b813-760903742baa

**Comment by jacobthill** [comment]
Actually this one is better because it has the Language field as well: https://spotlight.dev.dlmenetwork.org/library/catalog/f552a083-92d9-4912-8fd9-c34c0893a36f

**Comment by ggeisler** [comment]
> The object type is made up of data from the primary + secondary fields, so should always be present (unless there's a mapping issue?)

Yeah, I definitely hope that's true and I think we should aim for that goal.

My plan is to keep Type (primary) and Type (secondary) displaying until we get data updates showing on -dev and then we can hopefully verify that we never see cases where there is a Type (primary) value without also seeing a Object type value. Once we know that is true, we can omit display of the Type (primary) and Type (secondary) fields.

(I'm sure it would be better to verify the reliable presence of an Object type value in the data itself somehow, rather than eyeballing records, but I'm not clear if there is an easy way to do that.)
