### ISSUE TITLE
Feedback on DLME-dev from Magda Gad, SUL Librarian (Arabic speaker)

### ISSUE THREAD

**Issue by caaster** [sul-dlss/dlme#800]
We don't know who would like to address these issues (or if so, how) so I'm not assigning the ticket right now. However, a heads up to @jacobthill @ggeisler @anarchivist 

@cbeer and I met briefly with Magda today, to ask a couple of questions and get her general impression of the DLME-dev site so far.

Here are the key points she made:
1. The Hijri calendar started at 622 AD (Gregorian), so it makes no sense to display any Hijri year as a negative number. Any year that started before the Hijri year "1" is not called a Hijri year, it is referred to in a different way. (#804)
2. The Arabic word used for the English the word "everything" (for search) is not the common translation.
3. It looks ok to have the date range slider (Arabic version) providing Arabic date ranges in Latin format. This is acceptable and not too confusing.
4. It is confusing to have records with data elements in English only. Why would there be an Arabic version of the site if there are items that only have English titles -- ie, they can't be searched in Arabic? This feels confusing and problematic, and would benefit from some user-facing explanation. (#805)

**Comment by jacobthill** [comment]
The perspective described in 1 above is not accurate. The negative numbers are a source of confusion but it is not true to say that "Any year that started before the Hijri year "1" is not called a Hijri year." The Hijra (or migration) of Muhammad from Mecca to Medina in 622 is used to mark the start of the Hijri calendar in the same way the supposed (though incorrectly) birth of Jesus marks the beginning of the Gregorian calendar. The connection with history before Jesus (e.g. the Old Testament) made the need for BC more obvious and thus BC dates are a more natural idea for those using the Gregorian calendar. Muslims referred to the time before Muhammad as the Age of Ignorance and simply dated things before Muhammad in a different calendar. We have drifted from that context however and now if Muslims want to refer to something before the Hijra they most often would use the Gregorian date. Islamic historians, however, do use the concept of BH (before Hijra) in the same way we use BCE in the West. We don't use negative dates to refer to BCE either, but this is a requirement of the technology. The proposed solution is to keep BH dates but change the display so the '15 BH' is displayed instead of '-15'. This solution is not perfect but it is the preferred solution by a majority of the curatorial advisors. We are still awaiting feedback from QNL.

**Comment by jacobthill** [comment]
Closing this as each point is addressed in other tickets:

1. https://github.com/sul-dlss/dlme/issues/845
2. https://github.com/sul-dlss/dlme/issues/828
3. https://github.com/sul-dlss/dlme/issues/890
4. Drafted 'Searching this site' blurb; translation in progress. Will appear [here](https://spotlight.dev.dlmenetwork.org/library/about/searching-this-site) when finished
