### ISSUE TITLE
Contextualize data provided by third parties so it's more clear why data in other languages may be displaying 

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/dlme#805]
It is confusing to have records with data elements in English only. Why would there be an Arabic version of the site if there are items that only have English titles -- ie, they can't be searched in Arabic? This feels confusing and problematic, and would benefit from some user-facing explanation.

Part of https://github.com/sul-dlss/dlme/issues/800

**Comment by ggeisler** [comment]
A couple of initial thoughts on this:

- The reverse is also true: there are records that only have a title or other field values in Arabic. Does the equivalent statement "Why would there be an English version of the site if there are items that only have Arabic titles?" concerning enough to worry about?
- It's probably a small subset, but I believe there are records that only have a title or other field values in languages other than English or Arabic (e.g., Turkish).

I could see adding an info flash message to the top of the results page to display some text altering the user to the fact that they might get more results for their search term if they enter that search term in other languages. But given my points above I'm a bit worried that to be accurate the statement will need to be stated in fairly general terms ("Items on this site are described in multiple languages. You might find more items that match your query if you enter search terms in languages other than [English | Arabic ].").

I'm not sure if that is helpful enough to justify showing the message. It might be. But I'm also wary of putting too much stock into the reactions of one person (even though it was great to get their feedback).

**Comment by ggeisler** [comment]
I created a stub of a [new about page](https://spotlight.dev.dlmenetwork.org/library/about/searching-this-site) called "Searching this site" on -dev. I'm focused on visual design at the moment so don't feel like writing up the text of that page is a priority for me, but I could help with that next week, if necessary. But I also don't need to be the one that works out how to convey what we want to convey on that page.

The new about page could be one part of a solution to the problem outlined in this ticket. The other part is alerting the user to the issue on the search results page. 

I think we'd only want to implement this part of the solution when the user conducts a search involving a search term. If it's just a facet-based search it doesn't seem appropriate to bother the user with this part of things.

The basic idea is to show a flash message at the top of the results page. This would only be shown on the first page of results, based on the assumption it's prominent enough that the user is likely to notice it when the results first come back. No need to keep bothering them with it on subsequent results pages.

I think the about page and the flash message are relevant whether the user is in the English or Arabic locale, so with this approach there is nothing special to do based on locale, although of course we'd need to do Arabic translations for the text in both places.

### Option A
The idea here is to keep the message as short as possible to minimize impact on the search results page, and just let the user know there is more to learn about how to search the site:

<img width="994" alt="Screen Shot 2019-12-12 at 1 52 07 PM" src="https://user-images.githubusercontent.com/101482/70757256-18b3e300-1cfc-11ea-9df9-b4502eab6ea9.png">


> You might see more results for your query by entering your search terms in another language.

where "entering your search terms in another language" is linked to the new "Searching this site" about page.

### Option B
One worry I have about Option A is that a user would have to see the flash message with every search, which could be annoying after they understand the language issue. So in this option we would add buttons to either:

- **Dismiss** - Close the flash message, similar to the close icon often seen on flash messages. This removes it from the page but the user would see it again in a subsequent search.
- **Don't show again** - This would require a cookie or something so we know not show the flash message again for this user, at least in this user session. If we could not show it to that user even in subsequent user sessions, that would be ideal.

<img width="994" alt="Screen Shot 2019-12-12 at 1 51 39 PM" src="https://user-images.githubusercontent.com/101482/70757269-21a4b480-1cfc-11ea-9ff4-2857bbcdde67.png">


The button styling is `btn btn-sm btn-outline-secondary` and `btn btn-sm btn-outline-primary` to minimize the visual impact of the buttons, since they are arguably not as important as other buttons on the page.

### Other options
I started with a couple of variations where the flash message text is bit longer and more informative, but they feel like they take too much vertical space on the page and I think the simpler text above is enough to convey the idea and let the user know there is a more info available. But I can post my longer options if people feel the ideas above are not sufficient.

**Comment by anarchivist** [comment]
I like Option B. I'd also be curious to get feedback from @jacobthill, @waynegraham and @ewaraksa on this.

**Comment by ewaraksa** [comment]
I like Option B as well. Thanks @ggeisler for thinking through this and for presenting a couple of options.

**Comment by waynegraham** [comment]
+1 for B

**Comment by jacobthill** [comment]
B sounds good to me as well
