### ISSUE TITLE
Change negative numbers to BH and BCE 

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#845]
<img width="882" alt="Screen Shot 2019-12-20 at 1 01 13 PM" src="https://user-images.githubusercontent.com/37662787/71280313-d5bfc400-2328-11ea-8024-dd8d0a6a83b4.png">
Can we change negatives in 'Date range' to BCE and BH respectively. They seems to be a source of confusion.

**Comment by ggeisler** [comment]
I like this solution for the date metadata value display if it's feasible.

This is probably more complicated, but if we could do something similar to the date range sliders, I think that could solve the problem there as well:

1. Change the x-axis labels on the graphs to use BCE and BH after the negative date labels, and remove the minus signs.
2. Change the date values that show in the input fields in the same way. 

If (2) is more complicated because mixing numbers and letters in the input fields not feasible, I think it still might be an improvement to change the labels on the graph as described above in (1) and keep the negatives in the input fields. That's not ideal, but I think users would probably get what's going on, and seeing the BCE and BH in the graph labels could help orient them.

**Comment by jacobthill** [comment]
<img width="642" alt="Hijri Date" src="https://user-images.githubusercontent.com/37662787/71283802-381bc300-232f-11ea-918a-59635810489e.png">
I drew this up to communicate a possible change to the curatorial advisors. I don't know if putting H or BH in the search field will work but it would make things much clearer. I'll drop the image in the date slider ticket as well.

**Comment by ggeisler** [comment]
Great, that's pretty much what I was imagining too. 

I'm not sure we have control over which years are displayed as the labels (I assume Flot picks labels that are evenly distributed based on the current date range), so even if we can add the BH and H labels, we might not always see year 1 as a label.

Also, I wonder if we really need the info flash message? I get that it's not common to refer to pre-year 1 in Hijri, so using BH is not a common thing, but maybe it's pretty obvious what it refers to when you see it in contrast to "H"? I just don't want to add unnecessary clutter to the UI, especially in the sidebar version, where showing this info flash will require adding at least two rows of height, maybe three. (If we do use it, it should go on a new row below the "Date range" heading.)
