### ISSUE TITLE
Need hyperlink from transform page to home page

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#853]
<img width="466" alt="Screen Shot 2020-01-14 at 2 26 25 PM" src="https://user-images.githubusercontent.com/37662787/72388308-6c8a6100-36da-11ea-8bb4-126be54376e4.png">

**Comment by ggeisler** [comment]
Should it?

There's already a prominent Home link in the main menu, available from every page of the site.

I envisioned reserving the DLME logo for linking to CLIR or some higher-level organizational page in the future, when the ownership of the site is more clear. 

I don't feel strongly about this and it's certainly easy to change a link. Mostly I'm not thrilled about offering users multiple pathways to the same thing when the main pathway (Home menu item) is pretty clear already. A secondary pathway opens up the possibility of confusion (users trying to figure out what the difference between the two are, when there is no difference).

**Comment by jacobthill** [comment]
<img width="1080" alt="Screen Shot 2020-01-14 at 2 46 04 PM" src="https://user-images.githubusercontent.com/37662787/72389198-ab211b00-36dc-11ea-8a1b-d940a5ee4736.png">

It doesn't have to. The problem is when I am transforming data there is no link back to the home page which I have to get to in order to reach the 'Exhibit dashboard'. Any link back to the home page from the transform page will work.

**Comment by ggeisler** [comment]
I see. Since this is a not an end-user need but just a curator need, I'd suggest we leave the topbar DLME icon alone and handle it in a place that does't have end-user implications.

I'd suggest we either the link to the exhibit home to the second DLME header ("A" in the screenshot below, which isn't part of the actual DLME exhibit site) or to be more explicit just add a new link to the Actions menu ("B" in the screenshot), as the first link under the Actions heading.

<img width="1013" alt="Screen Shot 2020-01-14 at 4 30 29 PM" src="https://user-images.githubusercontent.com/101482/72391760-55a03a80-36eb-11ea-9bf6-35c94c6b2660.png">

**Comment by ggeisler** [comment]
Oh, wait, I see now that for some reason the Actions sidebar is not part of the Transform Data page (there's room for it so not sure why it isn't there...).

So I guess option A in the screenshot above is more feasible, though it probably would be better overall to just add the sidebar to the Transform Data page and use option B.
