### ISSUE TITLE
Audit application config state between dev, stage, and prod and determine migration plan

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/dlme#860]
Facet labels, translations, browse categories, and images are inconsistent between dev, stage, and prod, and as we move towards launch, we want to ensure these are consistent.

**Comment by jacobthill** [comment]
@cbeer as I understand it this is ready for development. We essentially need a technical solution for migrating manual entries in dev to stage and prod. We don't want to have to try to keep the three sites synced by manually entering each change in all three sites.

**Comment by cbeer** [comment]
Can you describe in what ways the existing exhibit import/export function is insufficient?

**Comment by jacobthill** [comment]
I'm not sure that it is insufficient. It may work just fine. This is a remnant from last work cycle and may just be a misunderstanding. Maybe I just need to be trained on how to export settings from dev and import them to stage and prod. Things I know need to be exported/imported are:
- [ ] translations that are manually entered in dev
- [ ] facet labels that are manually entered in dev
- [ ] browse categories created in dev
- [ ] facet display and ordering that is manually configured in dev
- [ ] record view metadata field label display and ordered that is manually configured in dev

I may be missing others. Can all of these be exported and imported?

**Comment by cbeer** [comment]
Thanks, that checklist will be helpful.

**Comment by ggeisler** [comment]
Also curated page (homepage, about pages) content. Basically everything (if I remember correctly) that you can configure in the admin pages.

I'd first want to try exporting from current -prod and importing to -dev (I think, not sure if I'm missing a good reason not to do that) because the -prod configuration is more current than -dev (I think most of the -prod configuration is the result of work I did late last year; which was wiped out on -dev earlier this year. I redid some of it on -dev but not all). That would give us an improved starting point on -dev, and then going forward we can fine-tune the configuration on -dev throughout the workcycle, and ideally export from -dev and import to -prod when we're getting close to launch.

**Comment by jacobthill** [comment]
I added curated page content to the checklist above. I can work with @ggeisler to try the export from prod (and learn how to do it) and we can report back if the current import/export function has any limitations.

**Comment by camillevilla** [comment]
4/22: code updates have been deployed. Gary / Jacob to QA import / export today and write up some notes.

**Comment by ggeisler** [comment]
I exported https://spotlight.dev.dlmenetwork.org/library and imported the .json file to https://spotlight.stage.dlmenetwork.org/library. Some things appeared to work fine: (text content of pages, the two about page iframe-based forms), but other things didn't work as expected:

- Site masthead: background image didn't import
- Facets aren't replaced by the new facet configuration
- Browse category widget background images not imported
- Visibility of all metadata fields for all views are off; doesn't match the exported configuration
- Browse categories not replaced; it looks like the exported categories were added to the existing set
- Browse category background images not included in the import
- About page Contacts - I _think_ the imported ones were added to the existing ones, not replacing them
- Translations - Pages - Although I think the about pages imported correctly, it looks like the translated versions did not. I had created one translation version of an about page on -dev and it didn't show up on -stage
- Contact emails: I don't think this worked because we have two entries on -dev and three entries on -stage

There might be some other things, but because -stage already had some content and settings that matched what we have on -dev it's hard to be sure of some things. For a more thorough and reliable test I think I should be to import to a brand-new exhibit with some configuration settings that will be easier to detect if they are replaced or not, which I'm happy to do. But given the number of things that didn't work as expected, maybe I should give @cbeer a chance to look into some of this in case there's something obvious that produced these results. (Maybe I did something wrong, but there's isn't much room for user error in this process.)

FWIW, when I created a new DLME exhibit locally and tried to import the -dev export file, I got this error:

```
Showing /Users/geisler/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/bundler/gems/spotlight-c31921015eea/app/views/spotlight/confirmation_mailer/confirmation_instructions.html.erb where line #5 raised:

Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true

**Comment by cbeer** [comment]
> About page Contacts - I think the imported ones were added to the existing ones, not replacing them

I think by design, imports will update or add to existing data and will not delete existing data.
