### ISSUE TITLE
Add email announcement opt in button

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#880]
- [ ] Determine where thee button should be displayed
- [ ] Add button: 
        
           What we currently have: https://clir.informz.net/clir/pages/DLMESignUp
           Existing iframe code: <iframe src="https://clir.informz.net/clir/pages/DLMESignUp" 
           width="1030" height="970" style="border:none;" scrolling="no"> </iframe>

**Comment by ggeisler** [comment]
@jacobthill To get a better idea of what you have in mind, I implemented a couple of rough approaches.

1. Add a link (you use the word "button", which we can explore, but a link is simpler) to a section of the existing about page. See bottom of https://spotlight.dev.dlmenetwork.org/library/about/about

That approach adds a minimum of info to the DLME site itself, which is the main advantage; instead it leads the user to the form outside of the exhibit context, which is the drawback, since the user has to know how to return to where they were (I suppose we could explore whether we could make the link open a new window, which is generally not a good thing to do, but possibly appropriate here).

2. Use a separate about page to embed the form directly. See https://spotlight.dev.dlmenetwork.org/library/about/announcements-and-updates for a first-pass at this.

The advantage of this approach is keeping the user on the DLME site. However, for this option to be viable I think we're going to need to be able to customize the contents of the page we're embedding. I have no idea what is possible but at a minimum we'd want to remove all the contents prior to the form fields. It would be very jarring to embed it as it currently looks.

**Comment by jacobthill** [comment]
@ggeisler I guess I would take option 2 if we can align the design of the form with the rest of the site. If not, then option one (with the new window) is ok, in my view.

**Comment by ggeisler** [comment]
I also think Option 2 is preferable from a UX standpoint so we can move forward on that, but that option will require CLIR to customize the page we're embedding. 

As a next step, I'll do a mockup to show how we would need the page customized to fit into the DLME about page, and then we can ask CLIR if they're willing and able to do the customization (or create an alternative version we can use for the embed).

**Comment by anarchivist** [comment]
I'm tagging @waynegraham here since he may have more insight into how Informz/Higher Logic is configurable (which is what I think we're using for the DLME list). I know that CLIR uses Informz for their own website, and uses an embedded iframe in the footer that looks to be styled similarly to the rest of the site: 

![Screen Shot 2020-04-01 at 12 02 57 PM](https://user-images.githubusercontent.com/73732/78176205-feb82080-7410-11ea-9fa3-edfa7a8ed128.png)

**Comment by waynegraham** [comment]
Informz isn't great on configuration, but you can write inline CSS overrides like it's 1999 (which is what I did with that footer). I think @ggeisler's option 2 is the best way forward with the limitations of embedding the Informz page. 

If you let me know what should be on the page, I'll do my best to override their weird CSS framework to make it look the same.

**Comment by ggeisler** [comment]
Thanks @waynegraham. 

I didn't look close enough at the URL Jacob provided and assumed that the iframe page was hosted by CLIR; if it's feasible for us to set up our own form with Informz and just point to the same submission endpoint your current form uses, that might be something I can do without requiring you to get involved.

**Comment by waynegraham** [comment]
So the link <https://clir.informz.net/clir/pages/DLMESignUp> is what got set up for this a while back when our outreach folks merged all the contact data. We can configure this inside of the Informz web portal, but there's not a way to create a form within your own application and post to their site (they've got some weird JavaScript stuff). 

I'm double checking on this, but as of the time that form on CLIR's home page was implemented, the only supported method to do any editing of the form was through the Informz interface and make it behave with inline CSS.

**Comment by ggeisler** [comment]
Okay, thanks. I thought maybe Informz was a service we could use directly to set up our own form, but it's sounding more like it's software CLIR uses. (Sorry for my ignorance; never heard of it before.)

If that's the case, then yes, maybe the way forward is for me to do a mockup of what we'd ideally want and you can look into how feasible it would be to configure at your end. Offhand I think what we'd want is the minimal form: input fields and submit button, with the appropriate page background color to blend into our page. All the other text surrounding the form I'd rather do on our page, outside of the iframe. But I'll provide a more exact mockup.

**Comment by waynegraham** [comment]
Informz is a service, but doesn't work like any of the other popular services (it kind of broke my mind the way it works) which I think is adding to the confusion here. 

We've got a support ticket in to see if they've implemented an API where you you can design and style the form inside of of Spotlight, but I'm not holding my breath. In the mean time, I went ahead and pulled the text off the form for the iframe; it should only be the fields now.

**Comment by ggeisler** [comment]
Got it.

Yeah, your update gets us a lot of the way there: https://spotlight.dev.dlmenetwork.org/library/about/announcements-and-updates

The main thing I'd still want to do is add `background-color: #f7f7f7;` (won't match current color exactly but that's what I intend to change the site body bg-color to).

The extra vertical space between the final input field and the captcha seems odd, but you might've already tried unsuccessfully to remove that?

**Comment by waynegraham** [comment]
I updated the background as best I could. There's a GDPR widget that is hidden for some reason and is apparently hidden if you're not from a GDPR area (but still has the space). I just moved it under the Sign Up button.

Let me know if button should be a different color, as well as the JS error message colors.

**Comment by ggeisler** [comment]
Nice, thanks @waynegraham. Let's stick with this for now, and I'll revisit when we finalize the overall visual design. But I think the updates you made help us see that this approach seems feasible. Any future request for changes should be limited to just the colors for the elements you mention.
