### ISSUE TITLE
Find new Arabic font

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#881]
Several data partners noted that the Arabic font chosen for DLME looks rather old fashioned and some letters are difficult to read. Can we find a more modern/legible font?

**Comment by ggeisler** [comment]
@jacobthill Just in case you aren't aware of it, here is some background on how we arrived at Mada as the DLME site font:

- I originally suggested "Amiri" as the Arabic font in #655. 
- @mejackreed investigated more thoroughly and suggested an alternative font, "Mada", for reasons he provided a lot of detail on here: #709.

I certainly take Arabic speakers concern about "Mada" and the request to find a better font seriously, especially if you heard the concern from more than one stakeholder, but want to make sure you're aware this is not just a visual design consideration.

Do you know if any of the stakeholders who expressed concern about Mada have enough knowledge of the use of web fonts to suggest a viable alternative Arabic font?

**Comment by jacobthill** [comment]
I think we can find a font that meets our criteria and addresses some of the concerns that were expressed. Ultimately we can defer to QNL. Here is a list of Arabic fonts with Latin and Arabic support: https://alinadigitalservices.com/arabic-google-fonts. I personally like the style and readability of the Markazi font.

**Comment by mejackreed** [comment]
Thanks for providing this useful link @jacobthill . I've created a little font playground for our use in choosing a font. You can view it here: https://0fc7p.codesandbox.io/

I don't see any problems off the bat. But there is a relationship between needing both the Arabic and Latin character sets as well as the font weights that we use in DLME (or have design needs for). I've tried to show this in the playground with a few different headings so that can be demonstrated a bit.

@ggeisler or @jacobthill let me know if you would like to have any additional fonts from https://fonts.google.com/?subset=arabic or other types of content added to the playground. Feel free to also share the playground with stakeholders or others if that is useful in making a decision.

**Comment by jacobthill** [comment]
I deferred this decision to QNL, awaiting response.

**Comment by jacobthill** [comment]
We have settled on Markazi Text. I think we can go ahead with this.

**Comment by ggeisler** [comment]
How about we say "tentatively" go ahead with this? We do need to consider whether the Latin version is acceptable as well. From the font samples it looks like the Latin version might be fine, but I'd want to see it in the context of the DLME site before saying it will work for sure. 

The Latin version does seem quite small, so if we go with it we'll probably need to adjust the font sizes were currently using. Again, seeing it in context will help.

For a first pass, I'd say we should go with 400, 500, and 700 weights, which I think might be what we're using with Mada now. Though I see this is also a "variable weight" font, but I don't understand that enough yet to know if it means we don't need to explicitly specify the weights we load.

**Comment by jacobthill** [comment]
That make sense.

**Comment by camillevilla** [comment]
we'll merge this PR and Gary will circle back for line-height review.
