### ISSUE TITLE
Reverse language selection values

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#885]
Reverse language selection values so that 'English' shows up in Arabic view and vice versa as in the images below from Qatar Digital Library
<img width="1567" alt="Screen Shot 2020-03-30 at 4 15 24 PM" src="https://user-images.githubusercontent.com/37662787/77957627-c2b27d80-72a1-11ea-90fd-b3cc90c03f1f.png">
<img width="1566" alt="Screen Shot 2020-03-30 at 4 15 34 PM" src="https://user-images.githubusercontent.com/37662787/77957643-c9d98b80-72a1-11ea-8c55-c41e041c4b1f.png">

**Comment by ggeisler** [comment]
Unless I'm misunderstanding something, I don't think we want to do this. The QNL example treats the language switcher as a toggle, rather than the Spotlight approach, which is a menu:

<img width="444" alt="Screen Shot 2020-03-30 at 1 31 26 PM" src="https://user-images.githubusercontent.com/101482/77959017-cdade380-728a-11ea-9da3-a8846aa41a89.png">


In a menu, you should display the currently active option, and the user uses the caret icon to reveal the list of other options. This is what we're doing.

**Comment by jacobthill** [comment]
@ggeisler I see. That is a helpful distinction. I was concerned that users who can't read both would not know how to move from one to another in case they were in the wrong one. But I think the caret icon should be universally understood.
