### ISSUE TITLE
QNL comment on strategic partners url behavior 

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#918]
"For the main strategic partners (QNL and Stanford), rather than opening the linked website on the
same webpage, I think it would be better to open in a new tab, to have both websites open, and
be able to go back and forth easily without losing any page."

@ggeisler I'm not sure if we need to just do this. I think if we have good reason to not implement the suggestion we can capture it here and I can try to convey it to QNL.

**Comment by ggeisler** [comment]
@jacobthill You're correct, we don't want to do this. It's not best practice to open links in new windows except in very specific cases, and I don't think this is a strong enough case to justify deviating from best practice. 

There are lots of resources on the Web, going back more than 10 years, that recommend not opening links in new windows. The basic idea is that the default behavior of hyperlinks is to open within the same window/tab, and it can be confusing or disorienting to users when that default and expected behavior doesn't happen. Basically we should trust that the user who wants to "have both websites open, and be able to go back and forth easily without losing any page" knows how to open a link in a new window or tab themselves.

I know you don't need convincing; the above is just in case you need to provide justification to QNL for why we will want to close this ticket without following their suggestion.

**Comment by jacobthill** [comment]
@ggeisler thanks, I think this is a good example of why we need to systematize the relationship with QNL. I will convey this in a tactful way.
