### ISSUE TITLE
Mirador RTL display issues

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/dlme#942]
I see that there's been some previous tracking of this work on ProjectMirador/mirador#2843, but I'm seeing some issues with the RTL presentation of Mirador.

* [x] Sidebar slides in from the left all the way to the right (reported on ProjectMirador/mirador#2843)
* [x] Sidebar panel is too close to sidebar compared with LTR (maybe reported on mirador ticket, less clear to me)
* [x] Annotations panel: "Highlight all" control and label are cut off
* [x] Search panel: "search terms" field label appears under search icon

### LTR display
![rtlm3-1](https://user-images.githubusercontent.com/73732/79015540-cd7ed500-7b21-11ea-8020-ffa7119a1707.gif)

### RTL display
![rtlm3-2](https://user-images.githubusercontent.com/73732/79015552-d40d4c80-7b21-11ea-92ad-df05530b4d2c.gif)

**Comment by ggeisler** [comment]
Some overlap with @anarchivist's to-dos in the original comment on this ticket, and with https://github.com/ProjectMirador/mirador/issues/2843, but I provided a bit more detail for the overlapped to-dos. 

Not mentioned below but still valid is:

- [ ] Sidebar slides in from the left all the way to the right (reported on ProjectMirador/mirador#2843); should slide out from the right

## Canvas navigation panel
<img width="626" alt="Screen Shot 2020-04-17 at 3 55 47 PM" src="https://user-images.githubusercontent.com/101482/79620269-35a25d80-80c4-11ea-88b6-6961a6317c05.png">

- [ ] **A**: Previous and next buttons should be swapped; next should point to the left and be on the left of the previous button.

- [ ] **B:** Page count (x of n string) is broken; the "of nnn" part should be with the rest of the message ("x") on the right side ("91 of 521")

## Window sidebar (global sidebar issues)

<img width="395" alt="Screen Shot 2020-04-17 at 3 59 49 PM" src="https://user-images.githubusercontent.com/101482/79620527-faecf500-80c4-11ea-9c3b-d04ec8ca1236.png">


- [ ] **C:** Flip horizontally the companion window icon, since it currently points to the right and in RtL mode new panels will open to the left.

- [ ] Companion window icon should be aligned at the very left of the panel (might be taken care of when the next issue is handled).

- [ ] **D:** Window panel title and other panel header content (e.g., menu in TOC, highlight toggle in Annotations) needs right-padding, same as left-padding on LtR version.

- [ ] **E:** The inside border on the vertical sidebar menu appears missing in RtL (or is probably still placed on the right, since the right edge looks a little darker than it should be).

- [ ] **F:** Smaller, colored border that indicates currently selected sidebar menu item needs shifting to inside edge of menu bar.

- [ ] **G:** The "Collapse sidebar" toggle is hidden under the right side of the panel. It needs to be moved to the left side of the panel.


### About panel
(I'm not suggesting anything for the panel content that comes from the IIIF manifest; I assume we rely on what we get from the manifest and we shouldn't try to rearrange manifest content -- ideally that would be covered by the manifest providing translated content).

<img width="832" alt="Screen Shot 2020-04-17 at 4 07 33 PM" src="https://user-images.githubusercontent.com/101482/79620691-93837500-80c5-11ea-8214-0ac4d09a7d14.png">

- [ ] **H:** The expand/collapse icons should be left-aligned in the panel, rather than next to the titles of the panel section they control.

- [ ] Even though I think we're just displaying the manifest content as-is, periods are shifted as if we're displaying RtL language text. We should leave the content completely alone and not do the usual RtL punctuation adjustments, etc.

### License panel
<img width="337" alt="Screen Shot 2020-04-17 at 4 10 07 PM" src="https://user-images.githubusercontent.com/101482/79620807-0391fb00-80c6-11ea-8b69-78378729c49c.png">

- [ ] This likely applies to other panels, but panel `<div>`s that get unequal left- and right-padding, such as the entire License `<div>` need those values reversed (e.g., `padding-left: 16px; padding-right: 8px;` needs to be `padding-left: 8px; padding-right: 16px;` in RtL).

### Annotations panel
<img width="337" alt="Screen Shot 2020-04-17 at 4 12 57 PM" src="https://user-images.githubusercontent.com/101482/79621631-f1fe2280-80c8-11ea-8333-fde856b98da4.png">

- [ ] **J:** Annotation content should be right-aligned in the panel, similar to content of other panels.

- [ ] **K:** The orange dot indicator shown when the object has annotations should be on the inside of the icon. Because we're doing that, we probably should also horizontally flip the annotations icon.

### Search panel

<img width="828" alt="Screen Shot 2020-04-17 at 4 25 00 PM" src="https://user-images.githubusercontent.com/101482/79621373-01c93700-80c8-11ea-8130-5817e58fb881.png">

- [ ] **L:** Search icon is in the correct place (assuming it gets moved a bit to the left with the general panel padding fix mentioned earlier); "search terms" placeholder label should be right-aligned in the panel.

Search results:
- [ ] **M:** orange results indicator dot on menu icon should move to the left of the search icon (this will probably look better if we also horizontally flip the search icon)

- [ ] **N:** padding flip needed for search result items

- [ ] **O:** margin on numbered icons needs reversed

- [ ] **P:** the "x of N" message is mixed up; should have the "of" between the numbers

- [ ] **Q:** the "next result" and "previous result" icons should be horizontally flipped (they are in the correct place, though)

**Comment by mejackreed** [comment]
Thanks for the great updates @ggeisler . One question about (A). The manifest in question explicitly sets the display as viewing left to right. https://www.qdl.qa/en/iiif/81055/vdc_100000000193.0x0000ea/manifest

In that case should the "Next" button be on the right as it currently is as that is the natural direction of the object?

**Comment by ggeisler** [comment]
Ah, I see. I think you're right, the canvas nav buttons should follow the manifest viewing direction, not the viewer language direction. Good catch.

**Comment by jacobthill** [comment]
@mejackreed has this been completed or do we need to keep this open?

**Comment by mejackreed** [comment]
Nope.. lets go ahead and close
