### ISSUE TITLE
Create dlmenetwork.org alias for each lists.stanford.edu email

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#950]
Alias all email lists with dlmenetwork.org and forward to lists.stanford.edu equivalent:
- [x] dlme-tech-team@lists.stanford.edu
- [x] dlme-contributors@lists.stanford.edu
- [x] dlme-feedback@lists.stanford.edu
- [ ] dlme-announce@lists.clir.org

**Comment by kamchan** [comment]
@jacobthill 

Is the use case for this just to give users ability to send email to a valid dlmenetwork.org email address, say dlme-feedback@dlmenetwork.org and have that email get forwarded to dlme-feedback@lists.stanford.edu.  Or are there other usages?

And only for the 4 lists?

**Comment by jacobthill** [comment]
I think the idea is to provide some long term stability. Eventually the project may move away from Stanford and the lists.stanford.edu email addresses would be discontinued. The others would remain and be transferred with the project. These are the only ones that need to be aliased since they're the only ones we are sharing publicly.

**Comment by kamchan** [comment]
emails sent to 

 dlme-tech-team@dlmenetwor.org
 dlme-contributors@dlmenetwork.org
 dlme-feedback@dlmenetwork.org
 dlme-announce@dlmenetwork.org

should now be forwarded to stanford/clir lists.

As a test, the dev email addresses (ie dlme-feedback@dev.dlmenetwork.org etc) will also go to the same lists.   Please make sure your lists are allowed to receive emails from your corresponding dlmenetwork.org above.  I added dlme-feedback@dlmenetwork.or since I was an assigned over of that list.
