### ISSUE TITLE
Rightmost column overlapping center

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#981]
<img width="1122" alt="Screen Shot 2020-04-29 at 12 35 55 PM" src="https://user-images.githubusercontent.com/37662787/80622031-3321fb00-8a16-11ea-8b7e-6cf666e1b7e0.png">

**Comment by ggeisler** [comment]
@jacobthill How important is it that the URL in the first column is easily visible? If it's not critical to see it at a glance, how about putting the URL value in a link as part of the Data path column, as shown below? You could still verify the URL value by hovering over the link and seeing it in the browser status bar (and of course you could click the link to go where you previously could go via the URL column).

### Option A

<img width="1001" alt="Screen Shot 2020-04-29 at 2 20 55 PM" src="https://user-images.githubusercontent.com/101482/80648316-d0842b80-8a24-11ea-9dbd-495c5f23deb8.png">


--- 

### Option B

If it's important you see the URL more easily, we could potentially follow the idea above but also put the URL into a `title` attribute, which you would see when you hover the link text, as shown below. We probably wouldn't want to use the `title` attribute like this for end-user info due to accessibility issues, but since this page is only going to be accessed by a very limited set of administrators, it might be okay.

<img width="1001" alt="Screen Shot 2020-04-29 at 2 21 44 PM" src="https://user-images.githubusercontent.com/101482/80648459-0d502280-8a25-11ea-9ff8-a88d3225f424.png">

---

For both options above we could alternatively link the Data path value itself and reduce the chance that rows will take more than one line:

<img width="1001" alt="Screen Shot 2020-04-29 at 2 26 43 PM" src="https://user-images.githubusercontent.com/101482/80648724-82235c80-8a25-11ea-87e5-b421df4752ac.png">


### Other options

If you really need to see the full URL value at a glance, I think we'd need to go to a more complex table layout where each row is split into two lines, with the URL value getting a full line and the other columns getting the other line (probably the top line, to keep the column headers clearly associated with the column values), but that would probably take a bit more development work and would probably make for a cluttered UI.

**Comment by jacobthill** [comment]
@ggeisler I don't need to see the url. As long as I can see the data provider any of the options would be fine.

**Comment by ggeisler** [comment]
Okay. I recommend we go with the version that adds the URL value as a link to the Data path value (the last screenshot in my previous comment, shown again below). That avoids having multiple links with the same text value.

<img width="1001" alt="80648724-82235c80-8a25-11ea-87e5-b421df4752ac" src="https://user-images.githubusercontent.com/101482/80742861-e7805780-8ad0-11ea-8802-7f1bae696155.png">
