### ISSUE TITLE
Outstanding translation issues:

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#996]
- [x] the word `Items` in the browse categories (only on home page; it is translated on the browse categories page) (projectblacklight/spotlight#2535 and projectblacklight/spotlight#2536)
<img width="838" alt="Screen Shot 2020-05-19 at 12 40 51 PM" src="https://user-images.githubusercontent.com/37662787/82354124-68df5180-99ce-11ea-8a99-7245510bc058.png">

- [x] `In partnership with` and `Project supported by` in footer (#995)
<img width="423" alt="Screen Shot 2020-05-19 at 12 44 31 PM" src="https://user-images.githubusercontent.com/37662787/82354254-91ffe200-99ce-11ea-9566-027ab33700df.png">

- [x] the title #995)
<img width="551" alt="Screen Shot 2020-05-19 at 12 46 37 PM" src="https://user-images.githubusercontent.com/37662787/82354477-d8554100-99ce-11ea-8d75-443e8c068e65.png">

- [x] `Find items by...` above facets (the current Arabic string is a translation of `Limit your search`; there is an [open PR](https://github.com/projectblacklight/blacklight/pull/2284))
<img width="266" alt="Screen Shot 2020-05-19 at 12 56 03 PM" src="https://user-images.githubusercontent.com/37662787/82355583-6978e780-99d0-11ea-8759-2a343468617d.png">

- [x] middot `Items`, `Data Contributors`, and `Item Contributors` in statistics dashboard looks like period after; add a space to make it clearer ([open PR](https://github.com/sul-dlss/dlme/pull/997))
<img width="258" alt="Screen Shot 2020-05-19 at 12 49 03 PM" src="https://user-images.githubusercontent.com/37662787/82355856-cbd1e800-99d0-11ea-8d98-059fcb70a0e5.png">

- [x] misplaced parenthesis in `By language` on statistics dashboard (this comes from the translation map and effects the language facet values also)
<img width="293" alt="Screen Shot 2020-05-19 at 1 04 20 PM" src="https://user-images.githubusercontent.com/37662787/82356369-71855700-99d1-11ea-8121-81b1db8c7d0f.png">

- [x] should title of CLIR be translated in sidebar on about page? not needed
<img width="298" alt="Screen Shot 2020-05-19 at 1 37 07 PM" src="https://user-images.githubusercontent.com/37662787/82359468-ea86ad80-99d5-11ea-9ef2-2fa36284cd88.png">

- [ ] `Suggest a collection` Google form (get QNL to translate in the same form)
<img width="1183" alt="Screen Shot 2020-05-19 at 1 39 59 PM" src="https://user-images.githubusercontent.com/37662787/82360480-75b47300-99d7-11ea-8b09-54f4fabcb16a.png">

- [ ] Email opt in
<img width="1195" alt="Screen Shot 2020-05-19 at 1 39 45 PM" src="https://user-images.githubusercontent.com/37662787/82360497-7e0cae00-99d7-11ea-9754-940a618faa41.png">

**Comment by camillevilla** [comment]
Title and footer should resolved once #995 is deployed.
Browse category issue should be resolved by projectblacklight/spotlight#2535

**Comment by camillevilla** [comment]
@jacobthill Chris and I will be working on getting things deployed to dev this afternoon. 

> should title of CLIR be translated in sidebar on about page? Probably not since its contact info but confirm with QNL

Spotlight currently doesn't support translation of the About Page contact info. Since this is a proper noun / organization name, it doesn't seem necessary to translate (Similar to BNF / Bibliothèque nationale de France)


> `Suggest a collection form`

Since this is provided by an iframe, we don't have the ability to translate this via Spotlight. Unfortunately, it doesn't seem like Google forms offers a good way to localize forms either. Some other options include:
1. Provide a different iframe on the Arabic version of the page. It could get annoying to manage two different feedback streams.
2. Update the existing form so that it includes both English and Arabic in the same form like so:
![Screen Shot 2020-05-20 at 10 53 35 AM](https://user-images.githubusercontent.com/5402927/82481623-73f7b780-9a8a-11ea-8178-84b29db9007b.png)

**Comment by jacobthill** [comment]
I like option 2 as well. I will request that QNL begin work on the translation. I think we can ignore the CLIR name in the sidebar. I was going to defer to QNL but given the technical difficulty I will just explain that we can't/don't need to translate it.

**Comment by jacobthill** [comment]
@waynegraham suggested another option for the Google form. Putting it here so its not forgotten. https://docs.google.com/forms/d/e/1FAIpQLScNsBO5e9CS2aO3lrAWdjI9nfPP24NEOUNomIFQ7LbrcUwPxg/formResponse

**Comment by ggeisler** [comment]
Does the second form load in the same iframe as the initial, language selection form?

If so, it seems like a potentially nice solution. It makes a lot of sense if we were just linking to the form outside of the DLME site, but I guess we'll need to see how it actually works in the context of the about page to be sure (e.g., does the second form load fast enough not to leave a weird hole in the about page, etc.).

**Comment by camillevilla** [comment]
@ggeisler Looked into this more and they're actually the same google form. I didn't realize that Google Forms lets you create conditional subsections.
![Screen Shot 2020-05-21 at 3 42 41 PM](https://user-images.githubusercontent.com/5402927/82613387-02973200-9b7a-11ea-845b-d7510de53ecd.png)

**Comment by ggeisler** [comment]
Oh cool @camillevilla thanks for investigating. I didn't realize that, either. This seems like a feasible option then.

**Comment by ggeisler** [comment]
I sort of have this working: https://dev.dlmenetwork.org/library/about/suggest-a-collection

Some drawbacks that I don't see a solution for:

- There's lots of extra white space on the first page of the form, since we need to vertically size the iframe to accommodate the longer second page of the form (unless we want scrollbars, in which case we could shorten the iframe height, but I don't like the way things look with the scrollbars too much)

- After you go to your selected language section, the form still has the initial "Preferred language" section visible. I don't see a way to have it go away the way its question goes away when you answer it. Annoying but probably not too noticeable by users.

- Although this enables us to provide an Arabic version of the questions, I don't see any way to present those questions as RtL. Apparently if you set your Google Drive to display in RtL that works will show the form in RtL, but it's not clear to me whether that holds true when the form is embedded in DLME. So maybe this will be okay for Arabic users who have their system generally configured for RtL, or maybe not?

If we want to go with this, someone will need to update Section 2 of the form with the Arabic versions of the question text.
