### ISSUE TITLE
Right align email opt in and google form in Arabic view

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#998]
@gary is this possible

Ideally these will both be translated. I'm not sure how that will work with the CLIR iframe but for the google form, I will need to create a new form in Arabic.

<img width="1195" alt="Screen Shot 2020-05-19 at 1 39 45 PM" src="https://user-images.githubusercontent.com/37662787/82359777-5ec15100-99d6-11ea-9960-fc72a8182191.png">

<img width="1183" alt="Screen Shot 2020-05-19 at 1 39 59 PM" src="https://user-images.githubusercontent.com/37662787/82359792-63860500-99d6-11ea-9266-5503d8d75f8e.png">

**Comment by ggeisler** [comment]
@jacobthill It's going to be challenging to provide Arabic versions of these two forms. Although I definitely support providing Arabic as much as possible, I wonder if it is worth the effort that will be required to deal with these two forms.

The main issue is that these forms are embedded in the page via an `<iframe>` widget. Because they are widget-based, we don't have direct control over the related HTML and associated text content as in a normal HTML page. So, for example, if you were to create a second, Arabic version of the Google form, we don't have (to my knowledge) any easy way to show the Arabic version of the form when the user is in the Arabic locale and the English version of the form when the user is in the English locale. 

We could style the content of the Google form so that when in the Arabic locale the text direction is RtL and the text aligns right, but it would still be the English text.

For the email list signup form, the problem is even more difficult. Again, because the content is in an iframe we're just embedding, we'd have to have Wayne create a second, Arabic version of the form, but then we still face the same issue of how to show the Arabic version of the form when the user is in the Arabic locale and the English version of the form when the user is in the English locale. 

And the particular service CLIR is using for the email form uses inline styles, so with that one I don't think we can even align the fields on the right, because the inline styles use absolute positioning and take precedence over any styles we add in the DLME stylesheets. (Although that part would be irrelevant if Wayne created an Arabic version of the form, since presumably he could change the inline styles to align right in that version.)

Also, in both cases, from a long-term maintenance perspective, it seems fragile to have two language-specific versions of these forms (every change or update requires remembering to touch both language versions).

I'm tagging @cbeer in case he has any ideas for dealing with two language-versions of the iframes, but unless he does, I think we might consider just living with English-only for these two forms.

**Comment by cbeer** [comment]
Yeah, I don't see how we could get away without language-specific forms because google and whatever other external service doesn't let us do that.

**Comment by jacobthill** [comment]
Ok we can ignore the Arabic versions for now. I will communicate this to QNL/CLIR. What about the right alignment?

**Comment by cbeer** [comment]
Again, we don't control the styling of those iframed components, so if they need to look different, they need  to be different forms.

**Comment by jacobthill** [comment]
Ok, I'm going to leave this open. We may not be able to fix this now but it looks pretty bad as it is currently. I will discuss with Wayne what we can do with the email opt-in and we can figure out what to do with the Google form the next work cycle.

**Comment by ggeisler** [comment]
I don't think the Google form looks too bad, because it is centered.

If Wayne can redo the CLIR email signup form to be similarly centered, that would improve things enough, in my opinion. It wouldn't look quite as good as it does now in English, but it would look better in Arabic, so that might be a reasonable compromise.
